az:
  a: us-east-2a
  b: us-east-2b
  c: us-east-2c

aws:
  asg:
    cd:
      alarm_scale_in_threshold:                 "50"
      alarm_scale_out_threshold:                "200"
      as_min_size:                              "27"
      as_max_size:                              "36"
      cron_scale_in:                            "00 23 * * 1-5"
      cron_scale_out:                           "30 11 * * 1-5"
      off_hour_desired:                         "18"
      on_hour_desired:                          "27"
      scale_in_out_weekdays:                    "true"
    cs:
      cron_scale_in:                            "00 23 * * 1-5"
      cron_scale_out:                           "30 11 * * 1-5"
      off_hour_desired:                         "3"
      on_hour_desired:                          "2"
      scale_in_out_weekdays:                    "false"
    is:
      as_min_size:                              "21"
      as_max_size:                              "30"
      cron_scale_in:                            "00 23 * * 1-5"
      cron_scale_out:                           "30 11 * * 1-5"
      off_hour_desired:                         "15"
      on_hour_desired:                          "21"
      scale_in_out_weekdays:                    "true"
    id:
      as_min_size:                              "7"
      as_max_size:                              "13"
    ix:
      asg_min_size:                             [1,1,1,1]
      stack_number:                             [1,2,3,4]
      zone_index:                               [0,1,2,0]