az:
  a: us-east-2a
  b: us-east-2b
  c: us-east-2c

xgemail_sxl_dbl:                                uri.vir1.sophosxl.com
xgemail_sxl_rbl:                                fur.vir1.sophosxl.com

aws:
  asg:
    cd:
      alarm_scale_in_threshold:                 "50"
      alarm_scale_out_threshold:                "200"
      as_max_size:                              "50"
      cron_scale_in:                            "00 00 * * 1-5"
      cron_scale_out:                           "45 10 * * 1-5"
      on_hour_desired:                          "33"
      scale_in_out_weekdays:                    "true"
    cs:
      cron_scale_in:                            "00 23 * * 1-5"
      cron_scale_out:                           "30 11 * * 1-5"
      on_hour_desired:                          "2"
      scale_in_out_weekdays:                    "false"
    is:
      as_max_size:                              "50"
      cron_scale_in:                            "00 00 * * 1-5"
      cron_scale_out:                           "45 10 * * 1-5"
      on_hour_desired:                          "33"
      scale_in_out_weekdays:                    "true"
      smtpd_auth_xcli_hosts:                    "87.229.68.231"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "20"
      throughput_mode:                          "provisioned"
