az:
  a: us-east-2a
  b: us-east-2b
  c: us-east-2c

aws:
  asg:
    is:
      as_min_size:                              "12"
      as_max_size:                              "18"
    id:
      as_min_size:                              "9"
      as_max_size:                              "15"
    ix:
      asg_min_size:                             [1,1,1,1,1,1]
      stack_number:                             [1,2,3,4,5,6]
      zone_index:                               [0,1,2,0,1,2]