az:
  a: us-east-2a
  b: us-east-2b
  c: us-east-2c

aws:
  asg:
    cd:
      alarm_scale_in_threshold:                 "50"
      alarm_scale_out_threshold:                "200"
      as_min_size:                              "15"
      as_max_size:                              "36"
      cron_scale_in:                            "00 23 * * 1-5"
      cron_scale_out:                           "45 10 * * 1-5"
      on_hour_desired:                          "27"
      scale_in_out_weekdays:                    "true"
    cs:
      cron_scale_in:                            "00 23 * * 1-5"
      cron_scale_out:                           "30 11 * * 1-5"
      on_hour_desired:                          "2"
      scale_in_out_weekdays:                    "false"
    is:
      as_min_size:                              "15"
      as_max_size:                              "36"
      cron_scale_in:                            "00 23 * * 1-5"
      cron_scale_out:                           "30 11 * * 1-5"
      on_hour_desired:                          "27"
      scale_in_out_weekdays:                    "true"
      smtpd_auth_xcli_hosts:                    "87.229.68.231"
    id:
      as_min_size:                              "7"
      as_max_size:                              "13"
    ix:
      asg_min_size:                             [1,1,1,1]
      stack_number:                             [1,2,3,4]
      zone_index:                               [0,1,2,0]
    mfis:
      as_min_size:                              "6"
      as_max_size:                              "24"
      instance_size:                            "m5a.2xlarge"
      on_hour_desired:                          "6"
    mfos:
      as_min_size:                              "6"
      as_max_size:                              "24"
      instance_size:                            "m5a.2xlarge"
      on_hour_desired:                          "6"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "20"
      throughput_mode:                          "provisioned"