az:
  a: us-east-2a
  b: us-east-2b
  c: us-east-2c

aws:
  asg:
    cd:
      alarm_scale_in_threshold:                 "50"
      alarm_scale_out_threshold:                "200"
      as_min_size:                              "9"
      as_max_size:                              "18"
    is:
      as_min_size:                              "12"
      as_max_size:                              "18"
    id:
      as_min_size:                              "7"
      as_max_size:                              "13"
    ix:
      asg_min_size:                             [1,1,1,1]
      stack_number:                             [1,2,3,4]
      zone_index:                               [0,1,2,0]