#!/bin/bash
# Downloads an S3 object from the appropriate S3 bucket

set -e

if [ "$#" -ge 4 ]; then
    ACCOUNT="$1"
    BUCKET="$2"
    BUCKETOBJECT="$3"
    LOCALOBJECT="$4"

    LOCATIONCONSTRAINT=$(aws s3api get-bucket-location --bucket $BUCKET | grep LocationConstraint | awk '{print $2}' | tr -d ',"')

    echo "Download S3 object '$BUCKETOBJECT' from bucket '$BUCKET' to local '$LOCALOBJECT'..."

    if [ -z "$LOCATIONCONSTRAINT" ] ; then
        aws s3api get-object --bucket $BUCKET --key $LOCALOBJECT $LOCALOBJECT
    else
        aws --region $LOCATIONCONSTRAINT s3api get-object --bucket $BUCKET --key $BUCKETOBJECT $LOCALOBJECT
    fi

    echo "Saved '$LOCALOBJECT'"
else
    echo "usage: $(basename $0) <account-environment> <bucket-name> <bucket-file> <local-file>"
    echo "ex: $(basename $0) dev5 cloud-inf-configs us-west-2/CloudStation/download.tar.gz /sophos/tmp/download.tar.gz"
    exit 2
fi