---
# Upload Files
# Documentation: http://ansible-manual.readthedocs.io/en/latest/s3_module.html
- name: "Upload the config file for {{stack.iam.role.cloud_email_beta_instance_roles}} to the config bucket {{cloud_applications}}"
  s3:
    mode:               put
    region:             "{{account.region}}"
    bucket:             "{{cloud_applications}}"
    object:             "{{build.branch}}/xgemail-infrastructure/roles_beta_instance_template.json"
    src:                "{{template.iam.role.roles_beta_instance_template}}"
    overwrite:          always

# CloudEmail IAM Roles for Beta delivery Instances
- name: "Deploy {{stack.iam.role.cloud_email_beta_instance_roles}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name:                                 "{{stack.iam.role.cloud_email_beta_instance_roles}}"
    state:                                      present
    region:                                     "{{account.region}}"
    disable_rollback:                           true
    template_url:                               "https://s3.amazonaws.com/{{cloud_applications}}/{{build.branch}}/xgemail-infrastructure/roles_beta_instance_template.json"
    template_parameters:
      Environment:                              "{{account.name}}"
      XgemailMsgHistoryBucketName:              "{{s3.msg_history_bucket}}"
      XgemailMsgHistoryMsBucketName:            "{{s3.msg_history_ms_bucket}}"
      XgemailPolicyBucketName:                  "{{s3.policy_bucket}}"
      XgemailQuarantineBucketName:              "{{s3.quarantine_bucket}}"
      XgemailInternetSubmitBucketName:          "{{s3.internet_submit_bucket}}"
      XgemailCustomerSubmitBucketName:          "{{s3.customer_submit_bucket}}"
      DeliveryDirectorDynamodbTableName:        "{{dynamodb.delivery_director_dynamodb}}"
      DeliveryDirectorBucketName:               "{{s3.delivery_director_bucket}}"
  register: cloud_email_beta_iam_output

- name: "Gather {{stack.iam.role.cloud_email_beta_instance_roles}} CloudFormation Stack Output"
  cloudformation_facts:
    stack_name: "{{stack.iam.role.cloud_email_beta_instance_roles}}"
    region: "{{account.region}}"
  register: cloud_email_beta_iam_output

- name: "Print {{stack.iam.role.cloud_email_beta_instance_roles}} CloudFormation Stack Output"
  debug:
    var: cloud_email_beta_iam_output
    verbosity: 3