---
# CloudEmail IAM Roles for Beta delivery Instances
- name: "Deploy {{stack.iam.role.cloud_email_beta_delivery_roles}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name:                                 "{{stack.iam.role.cloud_email_beta_delivery_roles}}"
    state:                                      present
    region:                                     "{{account.region}}"
    disable_rollback:                           true
    template:                                   "{{template.iam.role.roles_beta_delivery_template}}"
    template_parameters:
      Environment:                              "{{account.name}}"
      XgemailMsgHistoryBucketName:              "{{s3.msg_history_bucket}}"
      XgemailMsgHistoryMsBucketName:            "{{s3.msg_history_ms_bucket}}"
      XgemailCustomerSubmitBucketName:          "{{s3.customer_submit_bucket}}"
      MsgHistoryV2StreamName:                   "{{kinesis.firehose.msg_history_v2_stream_name}}"
      MsgHistoryV2BucketName:                   "{{s3.msg_history_v2_bucket_name}}"
      MsgHistoryV2DynamoDbTableName:            "{{dynamodb.msg_history_v2_dynamodb}}"
  register: iam_stack_output

- name: "Print {{stack.iam.role.cloud_email_beta_delivery_roles}} CloudFormation Stack Output"
  debug:
    var: iam_stack_output
    verbosity: 3

# IAM Policy for Beta Instances to Kinesis Firehose Delivery Stream
- name: "Deploy Beta EC2 Instances to Kinesis Firehose Log Shipper IAM Policy {{stack.iam.policy.policy_beta_publish_to_firehose}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:              "{{stack.iam.policy.policy_beta_publish_to_firehose}}"
    state:                   present
    region:                  "{{account.region}}"
    disable_rollback:        true
    template:                "{{template.iam.policy.policy_publish_to_firehose_template}}"
    template_parameters:
      Environment:           "{{account.name}}"
      FirehoseStreamArn:     "{{kinesis.firehose.arn_prefix}}{{kinesis.firehose.firehose_log_shipper_stream}}"
      RoleNames:             "{{iam_stack_output.stack_outputs.XgemailBetaDeliveryInstanceRole}}"
      PolicyName:            "{{iam.policy.policy_beta_publish_to_firehose}}"
  register: log_shipper_policy_output

- name: "Display Kinesis Firehose Log Shipper IAM Policy Stack Output for Beta instances"
  debug:
    var: log_shipper_policy_output
    verbosity: 2