ami:
  base:
    branch: "{{ build.branch | default('develop') }}"
    ami_parent_alternate_bugfix_branch: release/2017.50
    ami_parent_alternate_feature_branch: develop
    ami_parent_description: Sophos Cloud base amazon linux AMI
    ami_parent_name: Sophos-Cloud-base-amazon-linux-AMI
    ami_type: base-amazon-linux
    ami_version: latest
  xgemail:
    stack_name:                                             "ami-build-xgemail-{{ build.plan_key }}-{{ build.number }}"
    ami_bucket:                                             sophos-cloud-amis
    ami_build_timeout_minutes:                              "{{lookup('env','AMI_BUILD_TIMEOUT_MINUTES') | default('80') }}"
    ami_parent_alternate_bugfix_branch:                     "{{lookup('env','AMI_PARENT_ALTERNATE_BUGFIX_BRANCH') | default('develop') }}"
    ami_parent_alternate_feature_branch:                    "{{lookup('env','AMI_BUILD_TIMEOUT_MINUTES') | default('develop') }}"
    ami_parent_description:                                 "{{lookup('env','AMI_PARENT_DESCRIPTION') | default('Sophos Cloud base amazon linux AMI') }}"
    ami_type:                                               "{{lookup('env','AMI_TYPE') | default('xgemail') }}"
    connector_env:                                          "{{lookup('env','CONNECTOR_ENV') | default('45ad1c14-edde-48a1-a36c-e3e7c986998a') }}"
    region:                                                 "{{account.region }}"
    aes_decryption_key:                                     "{{lookup('env','AES_KEY') }}"
    ami_destination_regions:                                "{{lookup('env','COPYREGIONS') | default('eu-west-1 us-east-2 us-west-2 eu-central-1') }}"
    ami_launch_permissions:                                 "['750199083801' '855146673459' '769208163330' '050963334367' '455082247759' '283871543274' '382702281923' '859103266070' '202058678495' '843638552935']"
    application_name:                                       xgemail
    block_device_mappings_xvdf:                             "{{lookup('env','blockDeviceMappingsXvdf') | default('40') }}"
    block_device_mappings_xvdg:                             "{{lookup('env','blockDeviceMappingsXvdg') | default('50') }}"
    block_device_mappings_xvdh:                             "{{lookup('env','blockDeviceMappingsXvdh') | default('20') }}"
    branch:                                                 "{{build.branch}}"
    build:                                                  "{{build.number}}"
    build_id:                                               "{{build.result_key}}"
    environment:                                            hmr-core
    iam_profile:                                            sophos-cloud-image-setup
    instance_type:                                          t2.large
    key_pair_name:                                          ami-builder-key
    s3_cookbook_repository_url:                             "//cloud-applications/{{ build.branch }}/cookbooks.enc"
    s3_sophos_3rdparty_repository_url:                      //cloud-applications-3rdparty
    s3_sophos_apprepository_url:                            //cloud-applications
    vpc_security_group:                                     sg-1b470e7e
    vpc_subnet_id:                                          subnet-c5bb00a0
    image_name:                                             "hmr-core-{{ build.branch }}-xgemail"
