ami:
  branch: "{{ ansible_controller_ami_branch | default(build.branch) }}"

ec2_instance:
    stack_name:              "ami-build-xgemail-${bamboo.shortPlanKey}-${bamboo.buildNumber}"
    image_name:              "hmr-core-{{ ami.branch }}-ansible"
    availability_zones:      "{{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-VPC/output/AvailabilityZones', 'default=az-not-found') }}"
    vpc_id:                  "{{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-VPC/output/Vpc', 'default=vpcId-not-found') }}"
    instance_profile:        "{{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-IAMRoles/output/AnsibleInstanceProfile', 'default=iam-profile-not-found') }}"
    instance_type:           "m4.xlarge"
    security_group_base:     "{{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-SecurityGroups/output/SecurityGroupBase', 'default=securitygroup-base-not-found') }}"
    security_group_ansible:  "{{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-SecurityGroups/output/SecurityGroupAnsible', 'default=securitygroup-ansible-not-found') }}"
    zone_a:                  "{{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-VPC/output/PrivateSubnetDefaultA', 'default=zone-A-not-found') }}"
    zone_b:                  "{{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-VPC/output/PrivateSubnetDefaultB', 'default=zone-B-not-found') }}"
    zone_c:                  "{{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-VPC/output/PrivateSubnetDefaultC', 'default=zone-C-not-found') }}"

internal:
    package_filename:       "playbook.zip"
    package_path:           "{{ temp }}"

local:
    package_path:
    package_filename_path:  "{{ internal.package_path }}_{{ internal.package_filename }}"
    log_path:               "{{ log_path }}"

remote:
    s3_bucket:              "cloud-{{ account.name }}-ansible"
    s3_object:              "{{ build.branch }}/{{ temp }}_{{ internal.package_filename }}"
    s3_prefix:              "{{ build.branch }}/{{ temp }}"
    s3_prefix_output:       "playbook_results/{{ build.branch }}"
    kms_key:                "cloud-{{ account.name }}-configurations"





        "ParameterValue": "${bamboo.aeskey}"

        "ParameterValue": "${bamboo.AMI_BUILD_TIMEOUT_MINUTES}"

        "ParameterValue": "${bamboo.COPYREGIONS}"

        "ParameterValue": "${bamboo.LAUNCHPERMISSIONS}"

        "ParameterValue": "${bamboo.blockDeviceMappingsXvdf}"

        "ParameterValue": "${bamboo.planRepository.branchName}"

        "ParameterValue": "${bamboo.buildNumber}"

        "ParameterValue": "${bamboo.inject.AMI_PARENT_ID}"

        "ParameterValue": "${bamboo.javaBranchName}"

        "ParameterValue": "${bamboo.JDK_VERSION}"

        "ParameterValue": "${bamboo.POSTFIX_INSTALL}"

        "ParameterValue": "//cloud-applications/${bamboo.planRepository.branchName}/cookbooks.enc"

        "ParameterValue": "${bamboo.VPC_SECURITYGROUPID}"

        "ParameterValue": "${bamboo.VPC_SUBNETID}"
