---
- name: Debug
  debug:
    msg: "{{item.value.stack_name}} {{item.value.template}} {{item.value.template_parameters}}"
  with_dict: "{{aws.ec2.asg.cd}}"

- name: "Create CD ASG Stacks in AWS"
  async: 100
  poll: 0
  cloudformation:
    stack_name: "{{item.value.stack_name}}"
    state: "{{item.value.state}}"
    region:  "{{account.region}}"
    disable_rollback: true
    template: "{{item.value.template}}"
    template_parameters:
      AesDecryptionKey:                     "aes_decryption_key"
      AlarmTopicArn:                        "{{sns.arn_prefix}}{{sns.alarm_sns_topic}}"
      AmiId:                                "{{ami_parent_id}}"
      AutoScalingInstanceRoleArn:           "{{cloud_email_iam_output.stack_outputs.AutoScalingInstanceRoleArn}}"
      AutoScalingMinSize:                   ""
      AutoScalingMaxSize:                   "1"
      AutoScalingNotificationTopicARN:      "{{sns.arn_prefix}}{{sns.lifecycle_sqs_sns}}"
      AvailabilityZoneIndex:                loop
      AvailabilityZones:                    "{{account.region}}a, {{account.region}}b, {{account.region}}c"
      BastionSecurityGroup:                 "{{cloud_email_sg_output.stack_outputs.SecurityGroupBastion}}"
      Branch:                               "{{build.branch}}"
      BuildVersion:                         "{{build.result_key}}"
      BundleVersion:                        "{{build.number}}"
      EbsMinIops:                           "100"
      Environment:                          "{{account.name}}"
      HealthCheckGracePeriod:               ""
      HealthCheckType:                      ELB
      InstanceProfile:                      "{{cloud_email_iam_output.stack_outputs.XgemailDeliveryInstanceProfile}}"
      InstanceType:                         ""
      JavaServiceType:                      ""
      KeyName:                              ""
      LoadBalancerName:                     "{{elb_stack_output.stack_outputs.LoadBalancerId}}"
      MailDomain:                           ""
      PostfixInstall:                       ""
      PublicIpAddressEnabled:               ""
      S3CookbookRepositoryURL:              "//cloud-{{account.name}}-templates/{{build.branch}}/cookbooks.enc"
      ScaleDownOnWeekends:                  ""
      ScaleDownCron:                        "{{cron_scale_down}}"
      ScaleUpCron:                          "{{cron_scale_up}}"
      SecurityGroups:                       "{{cloud_email_sg_output.stack_outputs.XgemailDeliverySecurityGroup}},{{cloud_email_sg_output.stack_outputs.SecurityGroupBase}}"
      StationVpcName:                       "{{vpc.cloud_station.name}}"
      VolumeSetId:                          loop
      VolumeTrackerSimpleDbDomain:          ""
      Vpc:                                  "{{cloud_email_vpc_output.stack_outputs.Vpc}}"
      VpcZoneIdentifiers:                   "{{cloud_email_vpc_output.stack_outputs.PrivateSubnetDefaultA}},{{cloud_email_vpc_output.stack_outputs.PrivateSubnetDefaultB}},{{cloud_email_vpc_output.stack_outputs.PrivateSubnetDefaultC}}"
      VpcName:                              "{{vpc.cloud_email.name}}"
      XgemailBucketName:                    "{{s3.customer_submit_bucket}}"
      XgemailDeliveryAddress:               "{{route53_stack_output.stack_outputs.NewRecord}}"
      XgemailMinSizeDataGB:                 ""
      XgemailMsgHistoryBucketName:          "{{s3.msg_history_bucket}}"
      XgemailMsgHistoryQueueUrl:            "{{sqs.url_prefix}}{{sqs.msg_history_sqs_queue}}"
      XgemailSnsSqsQueueUrl:                "{{sqs.url_prefix}}{{sqs.customer_delivery_sqs_queue_sns_listener}}"
      XgemailSubmitAddress:                 ""
      XgemailSxlDbl:                        "{{xgemail_sxl_dbl}}"
      XgemailSxlRbl:                        "{{xgemail_sxl_rbl}}"
  with_dict: "{{aws.ec2.asg.cd}}"
  register: cd_stack_async_results

- async_status:
    jid: "{{item.ansible_job_id}}"
  with_items: "{{cd_stack_async_results.results}}"
  register: cd_stack_async_poll_results
  until: "{{cd_stack_async_poll_results.finished}}"
  retries: 30