---
- name: "Deploy {{stack.route53.customer_delivery_a_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.customer_delivery_a_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      Environment:                   "{{account.name}}"
      RecordType:                    "A"
      ResourceRecords:               "{{cloud_station_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_station_vpc].stack_outputs.NatEipA}}"
      ServiceName:                   "outbound-{{cloud_station_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_station_vpc].stack_outputs.NatEipA | regex_replace('\.', '-'}}"
  register: route53_stack_output

- debug:
    var: route53_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{route53_stack_output.stack_outputs}}"
    verbosity: 2