# Load all the appropriate variables
- debug:
    msg: 'Load variables from {{ role_path }}'

- import_tasks: cd-elb-deploy.yml
  tags:
    - install
    - uninstall

- import_tasks: cd-route53-deploy.yml
  tags:
    - install
    - uninstall

- import_tasks: find-ami-id.yml
  tags:
    - install
    - uninstall

- import_tasks: cd-instance-deploy.yml
  tags:
    - install
    - uninstall
