---
# http://docs.ansible.com/ansible/latest/ec2_ami_find_module.html
- block:
    - name: "Find Xgemail AMI ({{build.branch}})"
      ec2_ami_find:
        name: "hmr-core-{{build.branch}}-{{ami_type}}-*"
        region: "{{account.region}}"
        owner: 843638552935
        is_public: no
        virtualization_type: hvm
        sort: creationDate
        sort_order: descending
        sort_end: 1
        no_result_action: fail
        ami_tags:
          Name:         "hmr-core-{{build.branch}}-{{ami_type}}-*"
          branch:       "{{build.branch}}"
          ami_type:     "{{ami_type}}"
      register: ec2_ami_find_output
  rescue:
    - name: "Find Base AMI ({{alternate_branch}})"
      ec2_ami_find:
        name: "hmr-core-{{alternate_branch}}-{{ami_type}}-*"
        region: "{{account.region}}"
        owner: 843638552935
        is_public: no
        virtualization_type: hvm
        sort: creationDate
        sort_order: descending
        sort_end: 1
        no_result_action: fail
        ami_tags:
          Name:         "hmr-core-{{alternate_branch}}-{{ami_type}}-*"
          branch:       {{alternate_branch}}
          ami_type:     "{{ami_type}}"
      register: ec2_ami_find_output
  always:
    - name: "Display EC2 AMI Find Output"
      debug:
        msg: "{{ec2_ami_find_output}}"
        verbosity: 3

    - name: "Display EC2 AMI Id"
      debug:
        msg: "{{ec2_ami_find_output.results[0].ami_id}}"

    - lineinfile:
        path: "{{playbook_dir}}/ami_id"
        line: 'ami_id={{ec2_ami_find_output.results[0].ami_id}}'
        state: present
        create: yes

    - lineinfile:
        path: "{{playbook_dir}}/ami_id"
        line: 'ami_build={{ec2_ami_find_output.results[0].tags.build}}'
        state: present
        create: yes
