aws_account_id: 202058678495
connector_core: 336331a9-4fb4-49f8-af16-c2bd51da1fcd
connector_env: 028d9fce-bcd9-49a5-a639-64486fe3374f
connector_env_newboo: 80b04967-1fe3-481f-a22a-fb7f99f615b5
hopper_public_ip:                               "198.144.101.108/32"
nat_eip: b
cloud_applications: cloud-prod-templates
mail_domain: p0.p.hmr.sophos.com
xgemail_iops_data_gb:                           "900"
xgemail_size_data_gb:                           "100"
aws:
  asg:
    is:
      alarm_scaling_enabled:                    "true"
      alarm_scale_in_threshold:                 "5000"
      alarm_scale_out_threshold:                "30000"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "m4.2xlarge"
    cd:
      alarm_scaling_enabled:                    "true"
      alarm_scale_in_threshold:                 "100"
      alarm_scale_out_threshold:                "500"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "c4.large"
    cx:
      asg_min_size:                             [1,1,1]
      instance_size:                            "c4.large"
    cs:
      alarm_scaling_enabled:                    "true"
      alarm_scale_in_threshold:                 "5000"
      alarm_scale_out_threshold:                "30000"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "m4.2xlarge"
    id:
      alarm_scaling_enabled:                    "true"
      alarm_scale_in_threshold:                 "100"
      alarm_scale_out_threshold:                "500"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "c4.large"
    ix:
      asg_min_size:                             [1,1,1]
      instance_size:                            "c4.large"
    es:
      as_min_size:                              "3"
      as_max_size:                              "12"
      as_min_service:                           "1"
      as_max_batch_size:                        "2"
      instance_size:                            "c4.large"
    ed:
      as_min_size:                              "3"
      as_max_size:                              "12"
      as_min_service:                           "1"
      as_max_batch_size:                        "2"
      instance_size:                            "c4.large"
    ird:
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "c4.large"

  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "5"
      throughput_mode:                          "provisioned"
  es:
    toc_elasticsearch_domain:
      state:                                    present
      ebs_volume_size:                          "300"
      master_node_type:                         "m4.large.elasticsearch"
      node_type:                                "m4.xlarge.elasticsearch"
      instance_number:                          "2"
      master_instance_number:                   "3"
      snapshot_start_hour:                      "4"
      zone_awareness:                           "true"