aws_account_id: 202058678495
connector_core: 336331a9-4fb4-49f8-af16-c2bd51da1fcd
connector_env: 028d9fce-bcd9-49a5-a639-64486fe3374f
connector_env_newboo: 80b04967-1fe3-481f-a22a-fb7f99f615b5
hopper_public_ip:                               "198.144.101.108/32"
nat_eip: b
cloud_applications: cloud-prod-templates
mail_domain: p0.p.hmr.sophos.com
xgemail_iops_data_gb:                           "900"
xgemail_size_data_gb:                           "100"
aws:
  asg:
    cd:
      instance_size:                            "c4.large"
    cs:
      asg_min_size:                             [1,1,1,1,1,1]
      instance_size:                            "m4.2xlarge"
    cx:
      instance_size:                            "c4.large"
    id:
      instance_size:                            "c4.large"
    is:
      asg_min_size:                             [1,1,1,1,1,1]
      instance_size:                            "m4.2xlarge"
    ix:
      instance_size:                            "c4.large"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "5"
      throughput_mode:                          "provisioned"
  es:
    toc_elasticsearch_domain:
      ebs_volume_size:                          "300"
      master_node_type:                         "m4.large.elasticsearch"
      node_type:                                "m4.xlarge.elasticsearch"
      instance_number:                          "2"
      master_instance_number:                   "3"
      snapshot_start_hour:                      "4"
      zone_awareness:                           "true"
