aws_account_id: 202058678495
o365_account_id: 314892681163
connector_core: 336331a9-4fb4-49f8-af16-c2bd51da1fcd
connector_env: 028d9fce-bcd9-49a5-a639-64486fe3374f
connector_env_newboo: 80b04967-1fe3-481f-a22a-fb7f99f615b5
hopper_public_ip:                               "198.144.101.108/32"
cloud_applications: cloud-prod-templates
mail_domain: p0.p.hmr.sophos.com
xgemail_size_data_gb:                           "100"
aws:
  asg:
    bd:
      alarm_scaling_enabled:                    "true"
      alarm_scale_in_threshold:                 "100"
      alarm_scale_out_threshold:                "500"
      as_min_size:                              "3"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "c5a.large"
    bx:
      asg_min_size:                             [1,1,1]
      instance_size:                            "c5a.large"
    cd:
      alarm_scale_in_enabled:                   "false"
      alarm_scale_out_enabled:                  "true"
      alarm_scale_in_threshold:                 "100"
      alarm_scale_out_threshold:                "500"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "m5a.large"
      newrelic_enabled:                         "true"
    cs:
      alarm_scaling_enabled:                    "false"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
<<<<<<< HEAD
      instance_size:                            "m5a.2xlarge"
=======
      instance_size:                            "m5.2xlarge"
      newrelic_enabled:                         "true"
>>>>>>> 23986898 (MD-3875 Updated CS templates with Newrelic integration)
      policy_target_value:                      "65"
    cx:
      asg_min_size:                             [ 1,1,1 ]
      instance_size:                            "m5a.large"
      newrelic_enabled:                         "true"
    dd:
      alarm_scaling_enabled:                    "true"
      alarm_scale_in_threshold:                 "100"
      alarm_scale_out_threshold:                "500"
      as_min_size:                              "3"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "c5a.large"
      newrelic_enabled:                         "true"
    dx:
      asg_min_size:                             [1,1,1]
<<<<<<< HEAD
      instance_size:                            "c5a.large"
=======
      instance_size:                            "c5.large"
      newrelic_enabled:                         "true"
>>>>>>> 0d225217 (MD-3875 Updated DX templates with Newrelic integration)
    ed:
      as_min_size:                              "3"
      as_max_size:                              "12"
      as_min_service:                           "1"
      as_max_batch_size:                        "2"
      instance_size:                            "c5a.large"
      newrelic_enabled:                         "true"
      policy_target_value:                      "80"
    es:
      as_min_size:                              "3"
      as_max_size:                              "12"
      as_min_service:                           "1"
      as_max_batch_size:                        "2"
      instance_size:                            "c5a.large"
      newrelic_enabled:                         "true"
      policy_target_value:                      "80"
    id:
      alarm_scaling_enabled:                    "true"
      alarm_scale_in_threshold:                 "100"
      alarm_scale_out_threshold:                "500"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "m5a.large"
      newrelic_enabled:                         "true"
    is:
      alarm_scale_in_enabled:                   "false"
      alarm_scale_out_enabled:                  "true"
      alarm_scale_in_threshold:                 "5000"
      alarm_scale_out_threshold:                "30000"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
<<<<<<< HEAD
      instance_size:                            "m5a.2xlarge"
=======
      instance_size:                            "m5.2xlarge"
      newrelic_enabled:                         "true"
>>>>>>> 19021e41 (MD-3875 Updated IS templates with Newrelic integration)
      policy_target_value:                      "85"
    ix:
      asg_min_size:                             [1,1,1]
<<<<<<< HEAD
      instance_size:                            "c5a.large"
=======
      instance_size:                            "c5.large"
      newrelic_enabled:                         "true"
<<<<<<< HEAD
>>>>>>> 23d68fe5 (MD-3875 Updated I templates with Newrelic integration)
    mfis:
      instance_size:                            "m5a.2xlarge"
=======
>>>>>>> fca36707 (MD-3875 Updated MFIS templates with Newrelic integration)
    mfid:
      instance_size:                            "m5a.large"
      newrelic_enabled:                         "true"
    mfis:
      instance_size:                            "m5.2xlarge"
      newrelic_enabled:                         "true"
    mfix:
      instance_size:                            "c5.large"
      newrelic_enabled:                         "true"
    mfos:
      as_min_size:                              "3"
      as_max_size:                              "6"
<<<<<<< HEAD
      instance_size:                            "m5a.2xlarge"
=======
      instance_size:                            "m5.2xlarge"
      newrelic_enabled:                         "true"
>>>>>>> d7af458b (MD-3875 Updated MFOS templates with Newrelic integration)
    mfod:
      as_min_size:                              "3"
      as_max_size:                              "6"
      instance_size:                            "m5a.large"
      newrelic_enabled:                         "true"
    mfox:
<<<<<<< HEAD
      instance_size:                            "c5a.large"
=======
      instance_size:                            "c5.large"
      newrelic_enabled:                         "true"
>>>>>>> 01cf4d9b (MD-3875 Updated MFOX templates with Newrelic integration)
    rd:
      as_min_size:                              "3"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "3"
      instance_size:                            "c5a.large"
      newrelic_enabled:                         "true"
      policy_target_value:                      "80"
    rx:
      asg_min_size:                             [1,1,1]
      instance_size:                            "c5.large"
      newrelic_enabled:                         "true"
    wd:
      alarm_scaling_enabled:                    "true"
      alarm_scale_in_threshold:                 "100"
      alarm_scale_out_threshold:                "500"
      as_min_size:                              "6"
      as_max_size:                              "12"
      as_min_service:                           "3"
      as_max_batch_size:                        "1"
      eip_count:                                "4"
      instance_size:                            "m5a.large"
      newrelic_enabled:                         "true"
    wx:
      asg_min_size:                             [1,1,1]
      eip_count:                                "6"
      instance_size:                            "m5a.large"
      newrelic_enabled:                         "true"
  ec:
    redis:
      xgemail_dqs:
        node_type:                             "cache.r5.large"
        at_rest_encryption:                    "true"
        automatic_failover:                    "true"
        number_of_nodes:                       "2"
        availability_zones:                    "{{az.a}},{{az.b}}"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "5"
      throughput_mode:                          "provisioned"
  es:
    toc_elasticsearch_domain:
      state:                                    present
      ebs_volume_size:                          "300"
      master_node_type:                         "m4.large.elasticsearch"
      node_type:                                "m4.xlarge.elasticsearch"
      instance_number:                          "2"
      master_instance_number:                   "3"
      snapshot_start_hour:                      "4"
      zone_awareness:                           "true"
external_ip_access:
  hopper:
    a:                                                            "64.86.143.220/32"
    b:                                                            "216.6.116.220/32"
    c:                                                            "198.144.101.108/32"
