aws:
  asg:
    cd:
      as_min_size:                              "0"
      as_max_size:                              "0"
    cs:
      as_min_size:                              "0"
      as_max_size:                              "0"
    cx:
      asg_min_size:                             [0,0,0]
    ed:
      as_min_size:                              "0"
      as_max_size:                              "0"
    is:
      as_min_size:                              "0"
      as_max_size:                              "0"
    id:
      as_min_size:                              "0"
      as_max_size:                              "0"
    ix:
      asg_min_size:                             [0,0,0,0]
    rd:
      as_min_size:                              "0"
      as_max_size:                              "0"
    rx:
      asg_min_size:                             [0,0,0]
    wd:
      as_min_size:                              "0"
      as_max_size:                              "0"
    wx:
      asg_min_size:                             [0,0,0]

az:
  a: eu-west-1a
  b: eu-west-1b
  c: eu-west-1c

xgemail_sxl_dbl: uri.ire1.sophosxl.com
xgemail_sxl_rbl: fur.ire1.sophosxl.com