as_min_cap_bastion: "1"
aws_account_id: 382702281923
connector_core: 336331a9-4fb4-49f8-af16-c2bd51da1fcd
connector_env: 4920461d-0e0a-4e25-a452-0c4ba556d7a7
connector_env_newboo: 3d547301-2d95-459a-bd50-fcad86b65c03
hopper_public_ip:                               "198.144.101.107/32"
spot_price:               ".07"
mail_domain: "p0.d3.hmr.sophos.com"
nat_eip: b
cloud_applications: "cloud-qa-templates"
xgemail_iops_data_gb: "100"
xgemail_size_data_gb: "100"
aws:
  asg:
    cd:
      instance_size:                            "c4.large"
    cs:
      instance_size:                            "m4.large"
    cx:
      instance_size:                            "c4.large"
    id:
      instance_size:                            "c4.large"
    is:
      instance_size:                            "m4.large"
    ix:
      instance_size:                            "c4.large"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "1"
      throughput_mode:                          "provisioned"
  es:
    toc_elasticsearch_domain:
      state:                                    present
      ebs_volume_size:                          "35"
      master_node_type:                         "t2.small.elasticsearch"
      node_type:                                "t2.medium.elasticsearch"
      instance_number:                          "2"
      master_instance_number:                   "0"
      snapshot_start_hour:                      "4"
      zone_awareness:                           "true"