aws_account_id: 382702281923
o365_account_id: 699592435858
connector_core: 336331a9-4fb4-49f8-af16-c2bd51da1fcd
connector_env: 4920461d-0e0a-4e25-a452-0c4ba556d7a7
connector_env_newboo: 3d547301-2d95-459a-bd50-fcad86b65c03
hopper_public_ip:                               "198.144.101.107/32"
mail_domain: "p0.d3.hmr.sophos.com"
cloud_applications: "cloud-qa-templates"
xgemail_size_data_gb: "100"
aws:
  asg:
    cd:
      instance_size:                            "t3a.medium"
      newrelic_enabled:                         "false"
    cs:
      instance_size:                            "m4.large"
      newrelic_enabled:                         "false"
    cx:
      instance_size:                            "t3a.medium"
      newrelic_enabled:                         "false"
    dd:
      newrelic_enabled:                         "false"
    dx:
      newrelic_enabled:                         "false"
    ed:
      newrelic_enabled:                         "false"
    es:
      newrelic_enabled:                         "false"
    id:
      instance_size:                            "c4.xlarge"
      newrelic_enabled:                         "false"
    is:
      instance_size:                            "m4.large"
      newrelic_enabled:                         "false"
    ix:
      instance_size:                            "c4.xlarge"
      newrelic_enabled:                         "false"
    mfid:
      newrelic_enabled:                         "false"
    mfis:
      newrelic_enabled:                         "false"
    mfix:
      newrelic_enabled:                         "false"
    mfod:
      newrelic_enabled:                         "false"
    mfos:
      newrelic_enabled:                         "false"
    mfox:
      newrelic_enabled:                         "false"
    rd:
      newrelic_enabled:                         "false"
    rx:
      newrelic_enabled:                         "false"
    wd:
      newrelic_enabled:                         "false"
    wx:
      newrelic_enabled:                         "false"
  ec:
    redis:
      xgemail_dqs:
        node_type:                             "cache.m5.large"
        at_rest_encryption:                    "false"
        automatic_failover:                    "true"
        number_of_nodes:                       "2"
        availability_zones:                    "{{az.a}},{{az.b}}"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "1"
      throughput_mode:                          "provisioned"
  es:
    toc_elasticsearch_domain:
      state:                                    present
      ebs_volume_size:                          "35"
      master_node_type:                         "t2.small.elasticsearch"
      node_type:                                "t2.medium.elasticsearch"
      instance_number:                          "2"
      master_instance_number:                   "0"
      snapshot_start_hour:                      "4"
      zone_awareness:                           "true"
external_ip_access:
  hopper:
    a:                                                            "64.86.143.221/32"
    b:                                                            "216.6.116.221/32"
    c:                                                            "198.144.101.107/32"
