as_min_cap_bastion: "1"
aws_account_id: 382702281923
connector_core: 336331a9-4fb4-49f8-af16-c2bd51da1fcd
connector_env: 4920461d-0e0a-4e25-a452-0c4ba556d7a7
connector_env_newboo: 3d547301-2d95-459a-bd50-fcad86b65c03
hopper_public_ip:                               "198.144.101.107/32"
instance_size_xgemail_spot_price:               ".16"
mail_domain: "p0.d3.hmr.sophos.com"
nat_eip: b
cloud_applications: "cloud-qa-templates"
xgemail_iops_data_gb: "100"
xgemail_size_data_gb: "100"
eu_central_1_hostedZoneName:                "sophos-email-qa-eu-central-1-monitor.com."
eu_central_1_resourceRecords:               "10 mx-01-eu-central-1.qa.hydra.sophos.com.,20 mx-02-eu-central-1.qa.hydra.sophos.com."
eu_west_1_hostedZoneName:                   "sophos-email-qa-eu-west-1-monitor.com."
eu_west_1_resourceRecords:                  "10 mx-01-eu-west-1.qa.hydra.sophos.com.,20 mx-02-eu-west-1.qa.hydra.sophos.com."
us_east_2_hostedZoneName:                   "sophos-email-qa-us-east-2-monitor.com."
us_east_2_resourceRecords:                  "10 mx-01-us-east-2.qa.hydra.sophos.com.,20 mx-02-us-east-2.qa.hydra.sophos.com."
us_west_2_hostedZoneName:                   "sophos-email-qa-us-west-2-monitor.com."
us_west_2_resourceRecords:                  "10 mx-01-us-west-2.qa.hydra.sophos.com.,20 mx-02-us-west-2.qa.hydra.sophos.com."
us_west_2_recipient_hostedZoneName:         "sophos-email-qa-us-west-2-recipient.com."
us_west_2_recipient_resourceRecords:        "10 inbound-smtp.qa.us-west-2.amazonaws.com."
eu_central_1_id:                            "6c5cba1d-35fe-4de1-b5f5-97f5e013df99"
eu_central_1_private_key:                   "sophos-email-qa-eu-central-1-monitor.com.key"
eu_central_1_public_key:                    "sophos-email-qa-eu-central-1-monitor.com.crt"
eu_central_1_public_thumb_print:            "sophos-email-qa-eu-central-1-monitor.com_sha1.txt"
eu_west_1_id:                               "16404cae-a875-45be-94eb-4d55bb974e9e"
eu_west_1_private_key:                      "sophos-email-qa-eu-west-1-monitor.com.key"
eu_west_1_public_key:                       "sophos-email-qa-eu-west-1-monitor.com.crt"
eu_west_1_public_thumb_print:               "sophos-email-qa-eu-west-1-monitor.com._sha1.txt"
tenant_id:                                  "baf0da6e-b644-43a5-98a8-e14ed39b8d02"
us_east_2_id:                               "3611d007-d145-4721-97bb-fb129bd2788c"
us_east_2_private_key:                      "sophos-email-qa-us-east-2-monitor.com.key"
us_east_2_public_key:                       "sophos-email-qa-us-east-2-monitor.com.crt"
us_east_2_public_thumb_print:               "sophos-email-qa-us-east-2-monitor.com_sha1.txt"
us_west_2_id:                               "d6c9b096-233d-409d-bb8e-07b4d5b1defb"
us_west_2_private_key:                      "sophos-email-qa-us-west-2-monitor.com.key"
us_west_2_public_key:                       "sophos-email-qa-us-west-2-monitor.com.crt"
us_west_2_public_thumb_print:               "sophos-email-qa-us-west-2-monitor.com_sha1.txt"
ses_rule_set_name:                          "us-west-2-rule-set"
inbound_mail_recipients:                    "us.west.2.qa@sophos-email-qa-us-west-2-monitor.com, eu.central.1.prod@sophos-email-qa-eu-central-1-monitor.com, eu.west.1.prod@sophos-email-qa-eu-west-1-monitor.com, us.east.2.prod@sophos-email-qa-us-east-2-monitor.com"
outbound_mail_recipients:                   "sophos-email-qa-us-west-2-recipient.com, monitor.recipient@sophos-email-qa-us-west-2-recipient.com"
domains:                                    "sophos-email-qa-eu-central-1-monitor.com, sophos-email-qa-us-west-2-monitor.com, sophos-email-qa-eu-west-1-monitor.com, sophos-email-qa-us-east-2-monitor.com, sophos-email-qa-us-west-2-recipient.com"
aws:
  asg:
    cd:
      instance_size:                            "c4.large"
    cs:
      instance_size:                            "m4.2xlarge"
    cx:
      instance_size:                            "c4.large"
    id:
      instance_size:                            "c4.large"
    is:
      instance_size:                            "m4.2xlarge"
    ix:
      instance_size:                            "c4.large"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "1"
      throughput_mode:                          "provisioned"
  es:
    toc_elasticsearch_domain:
      ebs_volume_size:                          "100"
      master_node_type:                         "t2.medium.elasticsearch"
      node_type:                                "m4.xlarge.elasticsearch"
      instance_number:                          "2"
      master_instance_number:                   "3"
      snapshot_start_hour:                      "4"
      zone_awareness:                           "true"