sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-trusty to install the stable release
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

services: docker

env:
  matrix:
  - INSTANCE=installation-tarball-1112-ubuntu-1604
  - INSTANCE=installation-binary-1112-ubuntu-1604
  - INSTANCE=installation-script-main-ubuntu-1604
  - INSTANCE=installation-script-test-ubuntu-1604
  - INSTANCE=installation-script-experimental-ubuntu-1604
  - INSTANCE=installation-package-1123-ubuntu-1204
  - INSTANCE=installation-package-1123-ubuntu-1404
  - INSTANCE=installation-package-1123-ubuntu-1604
  - INSTANCE=service-execute-ubuntu-1604
  - INSTANCE=service-execute-multi-ubuntu-1604
#  - INSTANCE=service-upstart-ubuntu-1204
#  - INSTANCE=service-upstart-ubuntu-1404
#  - INSTANCE=service-upstart-multi-ubuntu-1204
#  - INSTANCE=service-upstart-multi-ubuntu-1404
  - INSTANCE=service-systemd-ubuntu-1604
  - INSTANCE=service-systemd-multi-ubuntu-1604
  - INSTANCE=resources-1123-ubuntu-1604
  - INSTANCE=network-ubuntu-1604
  - INSTANCE=volume-ubuntu-1604
#  - INSTANCE=auto-ubuntu-1204
#  - INSTANCE=auto-ubuntu-1404
  - INSTANCE=auto-ubuntu-1604

# Ensure we make ChefDK's Ruby the default
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - before_script:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
    - script:
      - /opt/chefdk/embedded/bin/chef --version
      - /opt/chefdk/embedded/bin/cookstyle --version
      - /opt/chefdk/embedded/bin/cookstyle
      - /opt/chefdk/embedded/bin/rspec
