---
- file:
    path: '{{ role_path }}/BUILT'
    state: directory
    mode: 0750
  register:
    msg_output_work_dir

- name: "Import Account Variables."
  include_vars:
    extensions: ['yml']
    dir: "{{ account.name }}"
    depth: 1
  tags:
    - always

- name: "Include SSL Generation task."
  include_tasks: generate-certs.yml

- name: "Cleanup Temporary directories"
  include_tasks: cleanup.yml