ami:
  base:
    branch: "{{build.branch | default('develop')}}"
    ami_parent_alternate_bugfix_branch: "{{lookup('env','AMI_PARENT_ALTERNATE_BUGFIX_BRANCH')}}"
    ami_parent_alternate_feature_branch: "{{lookup('env','AMI_PARENT_ALTERNATE_FEATURE_BRANCH') | default('develop')}}"
    ami_parent_description: "{{lookup('env','AMI_PARENT_DESCRIPTION') | default('Sophos Cloud base amazon linux AMI')}}"
    ami_parent_name: "Sophos-Cloud-base-amazon-linux-AMI"
    ami_type: "base-amazon-linux"
    ami_version: "latest"