vpc:
  cloud_email:
    name: CloudEmail
lambda:
  inbound_monitor_receive_lambda_function:              "Xgemail-Monitor-Receive"
  inbound_monitor_send_lambda_function:                 "Xgemail-Monitor-Send"
  mf_inbound_monitor_receive_lambda_function:           "Xgemail-Mf-Inbound-Monitor-Receive"
  mf_inbound_monitor_send_lambda_function:              "Xgemail-Mf-Inbound-Monitor-Send"
  outbound_monitor_receive_lambda_function:             "Xgemail-Outbound-Monitor-Receive"
  outbound_monitor_send_lambda_function:                "Xgemail-Outbound-Monitor-Send"
  mf_outbound_monitor_receive_lambda_function:          "Xgemail-Mf-Outbound-Monitor-Receive"
  mf_outbound_monitor_send_lambda_function:             "Xgemail-Mf-Outbound-Monitor-Send"
  enc_outbound_monitor_receive_lambda_function:         "Xgemail-Encryption-Outbound-Monitor-Receive"
  enc_outbound_monitor_send_lambda_function:            "Xgemail-Encryption-Outbound-Monitor-Send"
  inbound_ms_monitor_receive_lambda_function:           "Xgemail-Inbound-MS-Monitor-Receive"
  inbound_ms_monitor_send_lambda_function:              "Xgemail-Inbound-MS-Monitor-Send"
s3:
  lambda_bucket:                                        "cloud-{{account.name}}-{{account.region}}-lambda"

template:
  iam:
    role:
      roles_xgemail_monitor_template:                   "{{role_path}}/files/cf_templates/roles_xgemail_monitor_template.json"
  lambda:
    lambda_xgemail_inbound_monitor_template:            "{{role_path}}/files/cf_templates/lambda_template.json"
    lambda_xgemail_outbound_monitor_template:           "{{role_path}}/files/cf_templates/lambda_outbound_template.json"
  route53:
    route53_record_basic_template:                      "{{role_path}}/../common/files/cf_templates/route53_record_basic_template.json"
    route53_record_template:                            "{{role_path}}/../common/files/cf_templates/route53_record_template.json"
  ses:
    ses_template:                                       "{{role_path}}/files/cf_templates/ses_template.json"
stack:
  iam:
    role:
      cloud_email_monitor_roles:                        "{{account.name}}-XgemailMonitorRoles"
  lambda:
    inbound_monitor_receive_lambda_function:            "{{account.name}}-Lambda-XgemailMonitorReceive"
    inbound_monitor_send_lambda_function:               "{{account.name}}-Lambda-XgemailMonitorSend"
    outbound_monitor_receive_lambda_function:           "{{account.name}}-Lambda-XgemailOutboundMonitorReceive"
    outbound_monitor_send_lambda_function:              "{{account.name}}-Lambda-XgemailOutboundMonitorSend"
    mf_inbound_monitor_receive_lambda_function:         "{{account.name}}-Lambda-XgemailMfInboundMonitorReceive"
    mf_inbound_monitor_send_lambda_function:            "{{account.name}}-Lambda-XgemailMfInboundMonitorSend"
    mf_outbound_monitor_receive_lambda_function:        "{{account.name}}-Lambda-XgemailMfOutboundMonitorReceive"
    mf_outbound_monitor_send_lambda_function:           "{{account.name}}-Lambda-XgemailMfOutboundMonitorSend"
    enc_outbound_monitor_receive_lambda_function:       "{{account.name}}-Lambda-XgemailEncryptionOutboundMonitorReceive"
    enc_outbound_monitor_send_lambda_function:          "{{account.name}}-Lambda-XgemailEncryptionOutboundMonitorSend"
    inbound_ms_monitor_receive_lambda_function:         "{{account.name}}-Lambda-XgemailInboundMSMonitorReceive"
    inbound_ms_monitor_send_lambda_function:            "{{account.name}}-Lambda-XgemailInboundMSMonitorSend"
  route53:
    email_monitor_com_route53:                          "{{vpc.cloud_email.name}}-mx-sophos-email-monitor-com"
    email_monitor_net_route53:                          "{{vpc.cloud_email.name}}-mx-sophos-email-monitor-net"
    email_monitor_org_route53:                          "{{vpc.cloud_email.name}}-mx-sophos-email-monitor-org"
    email_monitor_us_route53:                           "{{vpc.cloud_email.name}}-mx-sophos-email-monitor-us"
    email_recipient_com_route53:                        "{{vpc.cloud_email.name}}-mx-sophos-email-recipient-com"
    mf_monitor_euw1_route53:                            "{{vpc.cloud_email.name}}-mx-mf-inbound-monitor-eu-west-1"
    mf_monitor_euc1_route53:                            "{{vpc.cloud_email.name}}-mx-mf-inbound-monitor-eu-central-1"
    mf_monitor_use2_route53:                            "{{vpc.cloud_email.name}}-mx-mf-inbound-monitor-us-east-2"
    mf_monitor_usw2_route53:                            "{{vpc.cloud_email.name}}-mx-mf-inbound-monitor-us-west-2"
    mf_monitor_recipient_usw2_route53:                  "{{vpc.cloud_email.name}}-mx-mf-monitor-recipient-us-west-2"
    inbound_ms_monitor_euw1_route53:                    "{{vpc.cloud_email.name}}-mx-inbound-ms-monitor-eu-west-1"
    inbound_ms_monitor_euc1_route53:                    "{{vpc.cloud_email.name}}-mx-inbound-ms-monitor-eu-central-1"
    inbound_ms_monitor_use2_route53:                    "{{vpc.cloud_email.name}}-mx-inbound-ms-monitor-us-east-2"
    inbound_ms_monitor_usw2_route53:                    "{{vpc.cloud_email.name}}-mx-inbound-ms-monitor-us-west-2"
    encryption_monitor_euw1_route53:                    "{{vpc.cloud_email.name}}-mx-encryption-monitor-eu-west-1"
    encryption_monitor_euc1_route53:                    "{{vpc.cloud_email.name}}-mx-encryption-monitor-eu-central-1"
    encryption_monitor_use2_route53:                    "{{vpc.cloud_email.name}}-mx-encryption-monitor-us-east-2"
    encryption_monitor_usw2_route53:                    "{{vpc.cloud_email.name}}-mx-encryption-monitor-us-west-2"
    encryption_monitor_recipient_usw2_route53:          "{{vpc.cloud_email.name}}-mx-encryption-monitor-recipient-us-west-2"
  ses:
    email_monitor_ses:                                  "{{account.name}}-SES"