az:
  a: eu-central-1a
  b: eu-central-1b
  c: eu-central-1c

xgemail_sxl_dbl: uri.ire1.sophosxl.com
xgemail_sxl_rbl: fur.ire1.sophosxl.com

aws:
  asg:
    cd:
      as_min_size:                              "6"
      as_max_size:                              "18"
      cron_scale_in:                            "00 17 * * 1-5"
      cron_scale_out:                           "30 05 * * 1-5"
      on_hour_desired:                          "9"
      scale_in_out_weekdays:                    "true"
    cs:
      cron_scale_in:                            "00 17 * * 1-5"
      cron_scale_out:                           "30 05 * * 1-5"
      on_hour_desired:                          "2"
      scale_in_out_weekdays:                    "false"
    is:
      as_min_size:                              "6"
      as_max_size:                              "18"
      cron_scale_in:                            "00 17 * * 1-5"
      cron_scale_out:                           "30 05 * * 1-5"
      on_hour_desired:                          "9"
      scale_in_out_weekdays:                    "true"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "8"
      throughput_mode:                          "provisioned"