name              'sophos-msg-snmpd'
maintainer        'Sophos Email'
maintainer_email  'SophosMailOps@sophos.com'
license           'All Rights Reserved'
description       'Installs/Configures SNMP'
long_description  'Installs/Configures SNMP'
version           '1.0.0'
