---
# Inbound Monitor Send Lambda Function
- name: "Create a zip archive of Inbound monitor send lambda function"
  archive:
    path:
    - /work/lambda/xgemail_monitor_send.js
    dest: "{{tmp_artifacts_dir}}/xgemail_monitor_send.zip"
    format: zip

- name: "Upload the Inbound monitor send lambda function for {{stack.lambda.inbound_monitor_send_lambda_function}} to the config bucket {{s3.lambda_bucket}}"
  s3:
    mode:               put
    region:             "{{account.region}}"
    bucket:             "{{s3.lambda_bucket}}"
    object:             "lambda/{{build.number}}/xgemail_monitor_send.zip"
    src:                "{{tmp_artifacts_dir}}/xgemail_monitor_send.zip"
    overwrite:          always

- name: "Deploy Inbound Monitor Send Lambda Function {{stack.lambda.inbound_monitor_send_lambda_function}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                             "{{stack.lambda.inbound_monitor_send_lambda_function}}"
    state:                                  present
    region:                                 "{{account.region}}"
    disable_rollback:                       true
    template:                               "{{template.lambda.lambda_xgemail_inbound_monitor_send_template}}"
    template_parameters:
      Environment:                          "{{account.name}}"
      FunctionName:                         "{{lambda.inbound_monitor_send_lambda_function}}"
      HandlerName:                          xgemail_inbound_monitor_send.monitor_handler
      IAMRoleArn:                           "{{iam_stack.stack_outputs.LambdaXgemailMonitorSendRoleArn}}"
      S3Bucket:                             "{{s3.lambda_bucket}}"
      S3Key:                                "lambda/{{build.number}}/xgemail_monitor_send.zip"
      ScheduleExpression:                   rate(1 minute)
  register: inbound_monitor_send_stack

- debug:
    var: inbound_monitor_send_stack
    verbosity: 3

- name: "Display Inbound Monitor Lambda Function Stack Output"
  debug:
    msg: "{{inbound_monitor_send_stack.stack_outputs}}"
    verbosity: 2

# Inbound Monitor Receive Lambda Function
- name: "Create a zip archive of Inbound monitor receive lambda function"
  archive:
    path:
    - /work/lambda/xgemail_monitor_receive.js
    dest: "{{tmp_artifacts_dir}}/xgemail_monitor_receive.zip"
    format: zip

- name: "Upload the Inbound monitor receive lambda function for {{stack.lambda.inbound_monitor_receive_lambda_function}} to the config bucket {{s3.lambda_bucket}}"
  s3:
    mode:               put
    region:             "{{account.region}}"
    bucket:             "{{s3.lambda_bucket}}"
    object:             "lambda/{{build.number}}/xgemail_monitor_receive.zip"
    src:                "{{tmp_artifacts_dir}}/xgemail_monitor_receive.zip"
    overwrite:          always

- name: "Deploy Inbound Monitor Receive Lambda Function {{stack.lambda.inbound_monitor_receive_lambda_function}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                             "{{stack.lambda.inbound_monitor_receive_lambda_function}}"
    state:                                  present
    region:                                 "{{account.region}}"
    disable_rollback:                       true
    template:                               "{{template.lambda.lambda_xgemail_inbound_monitor_receive_template}}"
    template_parameters:
      Environment:                          "{{account.name}}"
      FunctionName:                         "{{lambda.inbound_monitor_receive_lambda_function}}"
      HandlerName:                          xgemail_outbound_monitor_receive.monitor_handler
      IAMRoleArn:                           "{{iam_stack.stack_outputs.LambdaXgemailMonitorReceiveRoleArn}}"
      S3Bucket:                             "{{s3.lambda_bucket}}"
      S3Key:                                "lambda/{{build.number}}/xgemail_monitor_receive.zip"
      ScheduleExpression:                   rate(1 minutes)
  register: outbound_monitor_send_stack

- debug:
    var: outbound_monitor_send_stack
    verbosity: 3

- name: "Display Inbound Monitor Lambda Function Stack Output"
  debug:
    msg: "{{outbound_monitor_send_stack.stack_outputs}}"
    verbosity: 2