---
- name: "Deploy {{stack.route53.mx_01_02_sophos_email_monitor_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.mx_01_02_sophos_email_monitor_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      Environment:                   "{{account.name}}"
      RecordType:                    "MX"
      Region:                        "us-west-2"
      HostedZoneId:                  { Ref: "HostedZoneId" }
    with_items:
      - HostedZoneName
      - ResourceRecords
      - ServiceName
  register: email_monitor_stack_output

- debug:
    var: email_monitor_stack_output
    verbosity: 3

- name: "Display MX-01, MX-02 Route53 Stack Output"
  debug:
    msg: "{{email_monitor_stack_output.stack_outputs}}"
    verbosity: 2