---
- name: "Deploy {{stack.route53.email_monitor_com_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_monitor_com_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{us_west_2_hostedZoneName}}"
      ResourceRecords:               "{{us_west_2_resourceRecords}}"
  register: sophos_email_monitor_us_west_2_stack_output

- debug:
     var: sophos_email_monitor_us_west_2_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_monitor_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.email_monitor_net_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_monitor_net_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{eu_central_1_hostedZoneName}}"
      ResourceRecords:               "{{eu_central_1_resourceRecords}}"
  register: sophos_email_monitor_eu_central_1_stack_output

- debug:
     var: sophos_email_monitor_eu_central_1_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_monitor_eu_central_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.email_monitor_org_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_monitor_org_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{eu_west_1_hostedZoneName}}"
      ResourceRecords:               "{{eu_west_1_resourceRecords}}"
  register: sophos_email_monitor_eu_west_1_stack_output

- debug:
     var: sophos_email_monitor_eu_west_1_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_monitor_eu_west_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.email_monitor_us_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_monitor_us_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{us_east_2_hostedZoneName}}"
      ResourceRecords:               "{{us_east_2_resourceRecords}}"
  register: sophos_email_monitor_us_east_2_stack_output

- debug:
     var: sophos_email_monitor_us_east_2_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_monitor_us_east_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.email_recipient_com_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_recipient_com_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{us_west_2_recipient_hostedZoneName}}"
      ResourceRecords:               "{{us_west_2_recipient_resourceRecords}}"
  register: sophos_email_recipient_us_west_2_stack_output

- debug:
     var: sophos_email_recipient_us_west_2_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_recipient_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2