aws:
  ec2:
    asg:
      bastion:                                  ""
      cd:
        stack_name:                             ""
        template:                               ""
      cs:
        stack_name:                             ""
        template:                               ""
        template_parameters:
          AesDecryptionKey:                     ""
      cx:
        stack_name:                             ""
        template:                               ""
        template_parameters:
          AesDecryptionKey:                     ""
      id:
        stack_name:                             ""
        template:                               ""
        template_parameters:
          AesDecryptionKey:                     ""
      is:
        stack_name:                             ""
        template:                               ""
        template_parameters:
          AesDecryptionKey:                     ""
      ix:
        stack_name:                             ""
        template:                               ""
        template_parameters:
          AesDecryptionKey:                     ""

  s3:
    customer_submit_bucket:
      stack_name:                               "{{stack.s3.customer_submit_bucket}}"
      template:                                 "{{template.s3.s3_bucket_template}}"
      template_parameters:
        Environment:                            "{{account.name}}"
        RequireEncryptionForUploads:            sse-s3
        S3BucketName:                           "{{s3.customer_submit_bucket}}"
        S3LifeCycleDelete:                      14
        S3PolicyCreate:                         "true"
        S3PolicyPrincipalList:                  "arn:aws:iam::{{aws_account_id}}:role/build-system-{{account.name}}"
    emergency_inbox_bucket:
      stack_name:                               "{{stack.s3.emergency_inbox_bucket}}"
      template:                                 "{{template.s3.s3_bucket_template}}"
      template_parameters:
        Environment:                            "{{account.name}}"
        RequireEncryptionForUploads:            sse-s3
        S3BucketName:                           "{{s3.emergency_inbox_bucket}}"
        S3LifeCycleDelete:                      14
        S3PolicyCreate:                         "true"
        S3PolicyPrincipalList:                  "arn:aws:iam::{{aws_account_id}}:role/build-system-{{account.name}}"
    msg_history_bucket:
      stack_name:                               "{{stack.s3.msg_history_bucket}}"
      template:                                 "{{template.s3.s3_bucket_template}}"
      template_parameters:
        Environment:                            "{{account.name}}"
        RequireEncryptionForUploads:            sse-s3
        S3BucketName:                           "{{s3.msg_history_bucket}}"
        S3PolicyCreate:                         "true"
        S3PolicyPrincipalList:                  "arn:aws:iam::{{aws_account_id}}:role/build-system-{{account.name}}"
    msg_stats_bucket:
      stack_name:                               "{{stack.s3.msg_stats_bucket}}"
      template:                                 "{{template.s3.s3_bucket_template}}"
      template_parameters:
        Environment:                            "{{account.name}}"
        RequireEncryptionForUploads:            sse-s3
        S3BucketName:                           "{{s3.msg_stats_bucket}}"
        S3LifeCycleDelete:                      365
        S3PolicyCreate:                         "true"
        S3PolicyPrincipalList:                  "arn:aws:iam::{{aws_account_id}}:role/build-system-{{account.name}}"
    quarantine_bucket:
      stack_name:                               "{{stack.s3.quarantine_bucket}}"
      template:                                 "{{template.s3.s3_bucket_template}}"
      template_parameters:
        Environment:                            "{{account.name}}"
        RequireEncryptionForUploads:            sse-s3
        S3BucketName:                           "{{s3.quarantine_bucket}}"
        S3LifeCycleDelete:                      30
        S3PolicyCreate:                         "true"
        S3PolicyPrincipalList:                  "arn:aws:iam::{{aws_account_id}}:role/build-system-{{account.name}}"
    submit_bucket:
      stack_name:                               "{{stack.s3.submit_bucket}}"
      template:                                 "{{template.s3.s3_bucket_template}}"
      template_parameters:
        Environment:                            "{{account.name}}"
        RequireEncryptionForUploads:            sse-s3
        S3BucketName:                           "{{s3.submit_bucket}}"
        S3LifeCycleDelete:                      14
        S3PolicyCreate:                         "true"
        S3PolicyPrincipalList:                  "arn:aws:iam::{{aws_account_id}}:role/build-system-{{account.name}}"
    policy_bucket:
      stack_name:                               "{{stack.s3.policy_bucket}}"
      template:                                 "{{template.s3.s3_policy_bucket_template}}"
      template_parameters:
        Environment:                            "{{account.name}}"
        S3BucketName:                           "{{s3.policy_bucket}}"
        SnsPolicyTopic:                         "{{sns.arn_prefix}}{{sns.policy_sns_topic}}"
        SnsRelayControlTopic:                   "{{sns.arn_prefix}}{{sns.relay_control_sns_topic}}"

  sqs:
    lifecycle_sqs_sns:
      stack_name:                               "{{stack.sqs.lifecycle_sqs_sns}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_sns_subscription_template}}"
      template_parameters:
        Branch:                                 "{{build.branch}}"
        Environment:                            "{{account.name}}"
        SubscriptionName:                       xgemail-lifecycle
    customer_delivery_sqs_queue:
      stack_name:                               "{{stack.sqs.customer_delivery_sqs_queue}}"
      state:                                    "absent"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.customer_delivery_sqs_queue}}"
    customer_submit_sqs_queue:
      stack_name:                               "{{stack.sqs.customer_submit_sqs_queue}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.customer_submit_sqs_queue}}"
    customer_delivery_sqs_queue_sns_listener:
      stack_name:                               "{{stack.sqs.customer_delivery_sqs_queue_sns_listener}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.customer_delivery_sqs_queue_sns_listener}}"
    internet_delivery_sqs_queue_sns_listener:
      stack_name:                               "{{stack.sqs.internet_delivery_sqs_queue_sns_listener}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.internet_delivery_sqs_queue_sns_listener}}"
    dqs_sqs_queue:
      stack_name:                               "{{stack.sqs.dqs_sqs_queue}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.dqs_sqs_queue}}"
    delay_sqs_queue:
      stack_name:                               "{{stack.sqs.delay_sqs_queue}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.delay_sqs_queue}}"
        DelaySeconds:                           "600"
    emergency_inbox_sqs_queue:
      stack_name:                               "{{stack.sqs.emergency_inbox_sqs_queue}}"
      state:                                    "absent"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.emergency_inbox_sqs_queue}}"
    emergency_inbox_sqs_queue_sns_listener:
      stack_name:                               "{{stack.sqs.emergency_inbox_sqs_queue_sns_listener}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.emergency_inbox_sqs_queue_sns_listener}}"
    internet_delivery_sqs_queue:
      stack_name:                               "{{stack.sqs.internet_delivery_sqs_queue}}"
      state:                                    "absent"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.internet_delivery_sqs_queue}}"
    internet_submit_sqs_queue:
      stack_name:                               "{{stack.sqs.internet_submit_sqs_queue}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.internet_submit_sqs_queue}}"
    msg_history_sqs_queue:
      stack_name:                               "{{stack.sqs.msg_history_sqs_queue}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.msg_history_sqs_queue}}"
    msg_history_sqs_queue_sns_listener:
      stack_name:                               "{{stack.sqs.msg_history_sqs_queue_sns_listener}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.msg_history_sqs_queue_sns_listener}}"
    msg_statistics_sqs_queue:
      stack_name:                               "{{stack.sqs.msg_statistics_sqs_queue}}"
      state:                                    "absent"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.msg_statistics_sqs_queue}}"
    msg_statistics_sqs_queue_sns_listener:
      stack_name:                               "{{stack.sqs.msg_statistics_sqs_queue_sns_listener}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.msg_statistics_sqs_queue_sns_listener}}"
    quarantine_sqs_queue:
      stack_name:                               "{{stack.sqs.quarantine_sqs_queue}}"
      state:                                    "absent"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.quarantine_sqs_queue}}"
    quarantine_sqs_queue_sns_listener:
      stack_name:                               "{{stack.sqs.quarantine_sqs_queue_sns_listener}}"
      state:                                    "present"
      template:                                 "{{template.sqs.sqs_simple_template}}"
      template_parameters:
        QueueName:                              "{{sqs.quarantine_sqs_queue_sns_listener}}"

  sns:
    alarm_sns_topic:
      stack_name:                               "{{stack.sns.alarm_sns_topic}}"
      template:                                 "{{template.sns.sns_template}}"
      template_parameters:
        SNSTopicEndpointProtocol:               email
        SNSTopicEndpointValue:                  cloud-inf-aws-alerts@sophos.com
        SNSTopicName:                           "{{sns.alarm_sns_topic}}"
    delay_sns_topic:
      stack_name:                               "{{stack.sns.delay_sns_topic}}"
      template:                                 "{{template.sns.sns_simple_template}}"
      template_parameters:
        TopicName:                              "{{sns.delay_sns_topic}}"
    deleted_events_sns_topic:
      stack_name:                               "{{stack.sns.deleted_events_sns_topic}}"
      template:                                 "{{template.sns.sns_simple_template}}"
      template_parameters:
        TopicName:                              "{{sns.deleted_events_sns_topic}}"
    internet_delivery_sns_topic:
      stack_name:                               "{{stack.sns.internet_delivery_sns_topic}}"
      template:                                 "{{template.sns.sns_simple_template}}"
      template_parameters:
        TopicName:                              "{{sns.internet_delivery_sns_topic}}"
    quarantined_events_sns_topic:
      stack_name:                               "{{stack.sns.quarantined_events_sns_topic}}"
      template:                                 "{{template.sns.sns_simple_template}}"
      template_parameters:
        TopicName:                              "{{sns.quarantined_events_sns_topic}}"
    success_events_sns_topic:
      stack_name:                               "{{stack.sns.success_events_sns_topic}}"
      template:                                 "{{template.sns.sns_simple_template}}"
      template_parameters:
        TopicName:                              "{{sns.success_events_sns_topic}}"
    policy_sns_topic:
      stack_name:                               "{{stack.sns.policy_sns_topic}}"
      template:                                 "{{template.sns.sns_topic_policy_s3_template}}"
      template_parameters:
        TopicName:                              "{{sns.policy_sns_topic}}"
        SnsS3TopicPolicyBucket:                 "{{s3.policy_bucket}}"
        SnsS3TopicPolicyCreate:                 "true"
    relay_control_sns_topic:
      stack_name:                               "{{stack.sns.relay_control_sns_topic}}"
      template:                                 "{{template.sns.sns_topic_policy_s3_template}}"
      template_parameters:
        TopicName:                              "{{sns.relay_control_sns_topic}}"
        SnsS3TopicPolicyBucket:                 "{{s3.policy_bucket}}"
        SnsS3TopicPolicyCreate:                 "true"

deploy: yes
ami_parent_id: "{{ami_id}}"
as_min_cap_bastion: 1
cloudstation_hostedzone: hydra.sophos.com
cron_scale_down: "0 1 * * 6"
cron_scale_up: "0 4 * * 1"
nat_eip: a
xgemail_iops_data_gb: 100
xgemail_size_data_gb: 40
instance_size_xgemail_elasticsearch: t2.medium
instance_size_xgemail_internet_delivery: t2.small
instance_size_xgemail_delivery: t2.small
instance_size_xgemail_submit: t2.small
instance_size_xgemail_xdelivery: t2.small
xgemail_sxl_dbl: uri.cal1.sophosxl.com
xgemail_sxl_rbl: fur.cal1.sophosxl.com

aes_decryption_key:                             "{{lookup('env','AES_KEY')}}"
ami_id:                                         "{{lookup('env','AMI_ID')}}"
as_instance_role_arn:                           ""
as_min_size:                                    ""
as_max_size:                                    ""
as_notification_topic_arn:                      ""
az_index:                                       ""
az:                                             ""
bastion_sg:                                     ""
branch:                                         ""
build_version:                                  ""
bundle_version:                                 ""
ebs_min_iops:                                   ""
env:                                            ""
health_check_grace_period:                      ""
health_check_type:                              ""
instance_profile:                               ""
instance_type:                                  ""
java_service_type:                              ""
key_name:                                       ""
lb_name:                                        ""
mail_domain:                                    ""
postfix_install:                                ""
public_ip_address_enabled:                      ""
s3_cookbook_repo_url:                           ""
scale_down_on_weekends:                         ""
security_groups:                                ""
station_vpc_name:                               ""
volume_set_id:                                  ""
volume_tracker_simple_db_domain:                ""
vpc:                                            ""
vpc_zone_identifiers:                           ""
vpc_name:                                       ""
xgemail_bucket_name:                            ""
xgemail_delivery_address:                       ""
xgemail_min_size_db_gb:                         ""
xgemail_msg_history_bucket_name:                ""
xgemail_msg_history_queue_url:                  ""
xgemail_sns_sqs_queue_url:                      ""
xgemail_submit_address:                         ""