# Create a random string used to construct temporary path to store intermediate aggregated data
- shell: uuidgen
  register: uuid_build
  
- name: Set temp root directory
  set_fact:
    temp_dir_root: "{{ uuid_build.stdout | to_uuid }}"
  
- name: Create UUID string from uuidgen.output
  set_fact:
    temp_dir_common: "{{ uuid_build.stdout | to_uuid }}/common"

- file:
    state: directory
    recurse: true
    mode: 0755
    path: "./{{ temp_dir_common }}"

- copy:
    src: "cf_templates"
    dest: "./{{ temp_dir_common }}"