---

- name: "Gather {{stack.iam.cloud_station_region_roles}} CloudFormation Stack Output"
  cloudformation_facts:
    stack_name: "{{stack.iam.cloud_station_region_roles}}"
    region: "{{account.region}}"
  register: cloud_station_iam_region_output

- name: "Print {{stack.iam.cloud_station_region_roles}} CloudFormation Stack Output"
  debug:
    var: cloud_station_iam_region_output
    verbosity: 3

- name: "Print {{ lookup('cloudformation', '{{ account.region }}/{{ vpc.name }}-RegionIAMRoles/output/ApiInstRole') }} ApiInstRole Name"
  cloudformation_facts:
      region: "{{account.region}}"
      station_vpc_name: "{{station_vpc_name}}"

