---

- name: "Gather {{stack.events.rule.lifecycle_lambda}} CloudFormation Stack Output"
  cloudformation_facts:
    stack_name: "{{stack.events.rule.lifecycle_lambda}}"
    region: "{{account.region}}"
  register: lambda_instance_terminator_output

- name: "Print {{stack.events.rule.lifecycle_lambda}} CloudFormation Stack Output"
  debug:
    var: lambda_instance_terminator_output
    verbosity: 3
