---

- name: "Gather {{stack.region.iam.cloud_station_roles}} CloudFormation Stack Output"
  cloudformation_facts:
    stack_name: "{{stack.region.iam.cloud_station_roles}}"
    region: "{{account.region}}"
  register: cloud_station_region_iam_output

- name: "Print {{stack.region.iam.cloud_station_roles}} CloudFormation Stack Output"
  debug:
    var: cloud_station_region_iam_output
    verbosity: 3