- name: "Import Account Variables."
  include_vars:
    extensions: ['yml']
    dir: "{{account.name}}"
    depth: 1

- name: "Import Regional Variables."
  include_vars:
    extensions: ['yml']
    dir: "{{account.name}}/{{account.region}}"
    depth: 1

- name: "Include Create Temp Artifacts Task"
  include_tasks: create-temp-artifacts.yml

- name: "Dump all variables."
  debug:
    var: vars

- name: "Include {{stack.vpc.cloud_station_vpc}} CloudFormation Stack Output."
  include_tasks: get-cloudstation-vpc-output.yml