---
# Load all the appropriate variables
- include_tasks: ../tasks/util/load-vars-hierarchy.yml
  vars:
    hierarchy_dir: '{{ role_path }}'

- block:
  - include_tasks: create-temp-artifacts.yml
  when: deploy == True



