- name: "Import Account Variables."
  include_vars:
    extensions: ['yml']
    dir: "{{account.name}}"
    depth: 1
  tags:
    - always

- name: "Import Regional Variables."
  include_vars:
    extensions: ['yml']
    dir: "{{account.name}}/{{account.region}}"
    depth: 1
  tags:
    - always

- name: "Include Create Temp Artifacts Task"
  include_tasks: create-temp-artifacts.yml
  tags:
    - always

- name: "Dump all variables."
  debug:
    var: vars
  tags:
    - always

- name: "Include {{kms.key.alias}} KMS Key Metadata."
  include_tasks: get-kms-key-id.yml
  tags:
    - vpc

- name: "Include {{stack.vpc.cloud_station_vpc}} CloudFormation Stack Output."
  include_tasks: get-cloudstation-vpc-output.yml
  tags:
    - vpc
    - asg

- name: "Include {{stack.iam.role.cloud_station_region_roles}} CloudFormation Stack Output."
  include_tasks: get-cloudstation-region-iam-output.yml
  tags:
    - vpc

- name: "Include {{stack.vpc.cloud_email_vpc}} CloudFormation Stack Output."
  include_tasks: get-cloudemail-vpc-output.yml
  tags:
    - asg

- name: "Include {{stack.ec2.sg.cloud_email_security_groups}} CloudFormation Stack Output."
  include_tasks: get-cloudemail-security-group-output.yml
  tags:
    - asg

- name: "Include {{stack.iam.role.cloud_email_roles}} CloudFormation Stack Output."
  include_tasks: get-cloudemail-iam-output.yml
  tags:
    - asg

- name: "Include {{stack.sdb.volume_tracker_sdb}} CloudFormation Stack Output."
  include_tasks: get-simpledb-domain.yml
  tags:
    - asg

- name: "Include {{stack.efs.policy_efs_volume}} CloudFormation Stack Output."
  include_tasks: get-efs-volume-filesystem-id.yml
  tags:
    - asg

