version: '3'
services:
  savi:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/savi:latest
    container_name: savi
    hostname: savi
    domainname: sandbox.sophos
    ports:
      - '4010:4010'
    networks:
      - novanet

  mail-inbound:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/mail-inbound-service:latest
    container_name: mail-inbound
    hostname: mail-inbound
    domainname: sandbox.sophos
    ports:
      - '8099:8080'
    environment:
      - API_CONNECT_TIMEOUT_MS=30000
      - API_READ_TIMEOUT_MS=30000
      - APPLICATION_NAME=mail-inbound
      - AUTH_ENABLED=false
      - AWS_REGION=us-east-1
      - CONTENT_FILTERING_ENABLED=false
      - CUSTOMER_SUBMIT_STORAGE_ROOT=http://localstack:4576/s3/some-policy/path
      - CYREN_FAIL_OPEN_ON_FAILURE=false
      - CYREN_HOSTNAME=localhost
      - CYREN_NEW_MAPPINGS_ENABLED=true
      - DELAY_QUEUE_FEATURE_ENABLED=false
      - ENVIRONMENT=local
      - HIGH_RISK_URL_FEATURE_ENABLED=true
      - HIGH_RISK_URL_MAX_MESSAGE_SIZE_MB=10
      - HIGH_RISK_URL_MAX_URLS_PER_MESSAGE=100
      - HIGH_RISK_URL_MAX_URLS_PER_SXL_LOOKUP=15
      - INTERNET_SUBMIT_BUCKET=sandbox-cloudemail-xgemail-submit
      - INTERNET_SUBMIT_SERVICE_QUEUE=sandbox-Internet_Submit_Service_Queue
      - INTERNET_SUBMIT_STORAGE_ROOT=s3://sandbox-cloudemail-xgemail-submit
      - LAST_SEEN_AT_CACHE_EXPIRY_MINUTES=60
      - LAUNCHDARKLY_SOPHOS_CENTRAL_CLIENT_SDK_KEY=1234
      - LICENSE_CODE_CACHE_EXPIRY_MINUTES=30
      - LPAS_ENABLED=true
      - LPAS_ENDPOINT=http://lpas-fake:8080
      - LPAS_PASSWORD=lpasfakepwd
      - LPAS_USER=lpasfakeuser
      - MAILBOX_DLP_POLICY_FILE_PATH=config/policies/dlp/
      - MAILBOX_LOCAL_PART_FILE_PATH=config/policies/domains/
      - MAILBOX_POLICY_FILE_PATH=config/policies/endpoints/
      - MAIL_PIC_API_CREDENTIALS_BUCKET_NAME=cloud-sandbox-connections
      - MAIL_PIC_API_CREDENTIALS_FILE=mock_file
      - MAIL_PIC_API_ROOT_URL=http://mail-service:8080/mail/api/xgemail
      - MALWARE_SERVICE_ENABLED=true
      - MALWARE_SERVICE_REQUEST_QUEUE=sandbox-Malware_Request
      - MALWARE_SERVICE_RESPONSE_QUEUE=sandbox-Malware_Response
      - POLICY_BUCKET=sandbox-cloudemail-xgemail-policy
      - POLICY_STORAGE_ROOT=s3://sandbox-cloudemail-xgemail-policy
      - S3_ENDPOINT=http://localstack:4572
      - SASI_SERVICE_REQUEST_QUEUE=sandbox-SASI_Request
      - SASI_SERVICE_RESPONSE_QUEUE=sandbox-SASI_Response
      - SASI_VERDICT_INBOUND_ENABLED=false
      - SAVI_HOST_NAME=localhost
      - SAVI_PORT=4010
      - SMART_BANNER_API_URL=https://mock-cloudstation.sophos.com
      - SNS_ENDPOINT=http://localstack:4575
      - SPRING_PROFILES_ACTIVE=local
      - SQS_ENDPOINT=http://localstack:4576
      - SXL_URL=https://4.sophosxl.net/lookup
      - TINY_URL_DOMAINS=alturl.com,bit.ly,cli.re,easyurl.net,is.gd,rebrand.ly,tinyurl.com
      - TOC_HOST_NAME=protection.sophos.com
      - TOC_MAX_MESSAGE_MB_SIZE_FOR_REWRITE=10
      - TOC_SECRET_URI=file:///some-bucket/toc.secret-uri.com
      - XGEMAIL_SCAN_EVENTS_TOPIC=sandbox-xgemail-scan-events-SNS
    networks:
      - novanet

  malware-service:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/malware-service:latest
    container_name: malware-service
    hostname: malware-service
    domainname: sandbox.sophos
    ports:
    - '8050:8050'
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - APPLICATION_NAME=malware-service
      - AWS_REGION=us-east-1
      - ENVIRONMENT=local
      - AUTH_ENABLED=false
      - LPAS_ENABLED=true
      - LPAS_ENDPOINT=http://lpas-fake:8080
      - SQS_ENDPOINT=http://localstack:4576
      - S3_ENDPOINT=http://localstack:4572
      - SNS_ENDPOINT=http://localstack:4575
    networks:
      - novanet

  postfix-is:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:latest
    container_name: postfix-is
    hostname: internet-submit
    domainname: local.sandbox.hydra.sophos.com
    ports:
      - '5225:25' #SMTP
    environment:
      - HOSTNAME_EXTERNAL=internet-submit
      - INSTANCE_TYPE=internet-submit
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
    depends_on:
      - jilter-inbound
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
    networks:
      - novanet

  postfix-cd:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:latest
    container_name: postfix-cd
    hostname: customer-delivery
    domainname: local.sandbox.hydra.sophos.com
    environment:
      - HOSTNAME_EXTERNAL=customer-delivery
      - INSTANCE_TYPE=customer-delivery
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
      - DEBUG=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
    networks:
      - novanet

  message-history:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/message-history:latest
    container_name: message-history
    hostname: message-history
    domainname: sandbox.sophos
    mem_limit: 1024m
    ports:
      - "9010"
    environment:
      - APPLICATION_NAME=message-history
      - AUTH_ENABLED=false
      - AWS_REGION=us-east-1
      - BOUNCED_SQS_QUEUE_URL=sandbox-tf-message-history-bounced-events-sqs
      - CUSTOMER_SUBMIT_STORAGE_ROOT=http://localstack:4576/s3/some-policy/path
      - DELETED_SQS_QUEUE_URL=sandbox-tf-message-history-deleted-events-sqs
      - DELIVERY_STATUS_SQS_QUEUE_URL=sandbox-tf-message-history-delivery-status-sqs
      - ELASTICSEARCH_DOMAIN_ENDPOINT=elasticsearch
      - ELASTICSEARCH_DOMAIN_ENDPOINT_SCHEME=http
      - ELASTICSEARCH_PORT=9200
      - ENVIRONMENT=local
      - INTERNET_DELIVERY_SQS_QUEUE_URL=sandbox-tf-message-history-internet-delivery-sqs
      - INTERNET_SUBMIT_BUCKET=sandbox-cloudemail-xgemail-submit
      - INTERNET_SUBMIT_STORAGE_ROOT=s3://sandbox-cloudemail-xgemail-submit
      - LAUNCHDARKLY_SOPHOS_CENTRAL_CLIENT_SDK_KEY=1234
      - LPAS_ENABLED=true
      - LPAS_ENDPOINT=http://lpas-fake:8080
      - MAILBOX_DLP_POLICY_FILE_PATH=config/policies/dlp/
      - MAILBOX_LOCAL_PART_FILE_PATH=config/policies/domains/
      - MAILBOX_POLICY_FILE_PATH=config/policies/endpoints/
      - MESSAGE_HISTORY_STORAGE_ROOT=s3://sandbox-cloudemail-xgemail-msg-history
      - MSG_HISTORY_SQS_QUEUE_URL=sandbox-tf-message-history-msg-history-events-sqs
      - POLICY_STORAGE_ROOT=s3://sandbox-cloudemail-xgemail-policy
      - QUARANTINED_SQS_QUEUE_URL=sandbox-tf-message-history-quarantined-events-sqs
      - REDIRECTED_SQS_QUEUE_URL=andbox-tf-message-history-redirected-events-sqs
      - S3_ENDPOINT=http://localstack:4572
      - SNS_ENDPOINT=http://localstack:4575
      - SPRING_PROFILES_ACTIVE=local
      - SQS_ENDPOINT=http://localstack:4576
      - SUCCESS_SQS_QUEUE_URL=andbox-tf-message-history-success-events-sqs
      - WRITE_DOCUMENTS_TO_STORAGE=false
    restart: always

  elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:5.6.14
       ports:
         - "9200"
         - "9300"
       environment:
         - cluster.name=docker-cluster
         - discovery.type=single-node
         - http.host=0.0.0.0
         - xpack.security.enabled=false
         - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    networks:
      - novanet

  # postfix-xd:
  #   image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:latest
  #   container_name: postfix-xd
  #   hostname: extended-delivery
  #   domainname: local.sandbox.hydra.sophos.com
  #   environment:
  #     - HOSTNAME_EXTERNAL=extended-delivery
  #     - INSTANCE_TYPE=xdelivery
  #     - DEFAULT_REGION=local
  #     - DEFAULT_ENVIRONMENT=sandbox
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #     - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
  #   networks:
  #     - novanet

  jilter-inbound:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/jilter-common:latest
    container_name: jilter-inbound
    hostname: jilter-inbound
    domainname: sandbox.sophos
    environment:
      - JILTER_VERSION=current
      - DIRECTION=inbound
      - HOSTNAME_EXTERNAL=jilter-inbound
      - INSTANCE_TYPE=jilter-inbound
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
      - APPLICATION=
    ports:
      - '9876:9876'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
      - ~/.xgemail_sandbox/jilter/inbound/:/jilter/
      - ~/.xgemail_sandbox/policy_storage://policy-storage:rw
    networks:
      - novanet

  sasi-service-inbound:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/sasi-service:latest
    container_name: sasi-service-inbound
    hostname: sasi-service-inbound
    domainname: sandbox.sophos
    extra_hosts:
      - "sasi-daemon:172.16.199.111"
    external_links:
      - 'dynamodb:dynamo-service'
    environment:
      - aws.accessKeyId=$AWS_ACCESS_KEY_ID
      - aws.secretKey=$AWS_SECRET_ACCESS_KEY
      - logging.level.com.sophos=INFO
      - APPLICATION_NAME=sasi-inbound
      - COUNTER_DB_TABLE=None
      - enableLabsMonitoring=false
      - HISTORIAN_DB_TABLE=None
      - HISTORIAN_DB_TABLE_CREATE_DATE=None
      - SASI_REQUEST_QUEUE=sandbox-SASI_Request
      - SASI_RESPONSE_QUEUE=sandbox-SASI_Response
    volumes:
      - $XGEMAIL_HOME/xgemail-infrastructure/orchestrator/sasi/inbound-application.properties:/application.properties
    ports:
      - '18082:8080'
    depends_on:
      - "sasi-daemon"
    networks:
      - novanet

networks:
  novanet:
    external:
      name: nova_novanet
