version: '3'
services:
  sasi-daemon:
    image: email/sasi-daemon
    container_name: sasi-daemon-container
    hostname: sasi-daemon
    domainname: sandbox.sophos
    ports:
      - '32226:32223'
    networks:
      novanet:
        ipv4_address: 172.16.199.111

  elasticsearch:
    image: 'elasticsearch:1.7.5'
    ports:
      - '9200:9200'
      - '9300:9300'
    command: '-Des.cluster.name="quarantine.xgemail.sophos.cloud.com"'
    volumes:
      - '~/.nova/elasticsearch:/usr/share/elasticsearch/data'
    networks:
      - novanet

  mail-service:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/sophos_cloud_tomcat:latest
    container_name: mail-service
    hostname: mail-service
    domainname: sandbox.sophos
    ports:
      - '9898:8080'
    networks:
      - novanet
    dns:
      - 172.16.199.101
    links:
      - 'elasticsearch:elasticsearch-service'
    external_links:
      - 'postgres:postgres-service'
      - 'mongo:mongo-service'
      - 'memcache:memcache-service'
      - 'redis:redis-service'
      - 'kinesalite:kinesalite'
      - 'dynamodb:dynamo-service'
      - 'mailcatcher:mailcatcher-service'
    volumes:
      - $XGEMAIL_HOME/xgemail-infrastructure/orchestrator/sophos_cloud_tomcat_bootstrap.properties:/usr/local/etc/sophos/bootstrap.properties

networks:
  novanet:
    external:
      name: nova_novanet