version: '3'
services:
  cyren:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/cyren:latest
    container_name: cyren
    hostname: cyren
    domainname: sandbox.sophos
    ports:
      - '8088:8088' #cyren port
    networks:
      - novanet

  savi:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/savi:latest
    container_name: savi
    hostname: savi
    domainname: sandbox.sophos
    ports:
      - '4010:4010'
    networks:
      - novanet

  mail-inbound:
      image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/mail-inbound:latest
      container_name: mail-inbound
      hostname: mail-inbound
      domainname: sandbox.sophos
      ports:
        - '8080:8080'
      environment:
        - SPRING_PROFILES_ACTIVE=local
        - APPLICATION_NAME=mail-inbound
        - AWS_REGION=us-east-1
        - ENVIRONMENT=local
        - AUTH_ENABLED=false
        - LPAS_ENABLED=true
        - LPAS_ENDPOINT=http://lpas-fake:8080
        - API_CONNECT_TIMEOUT_MS=30000
        - API_READ_TIMEOUT_MS=30000
        - TOC_MAX_MESSAGE_MB_SIZE_FOR_REWRITE=10
        - TOC_HOST_NAME=protection.sophos.com
        - TOC_SECRET_URI=file:///some-bucket/toc.secret-uri.com
        - MAIL_PIC_API_CREDENTIALS_BUCKET_NAME=mock_s3_bucket
        - MAIL_PIC_API_CREDENTIALS_FILE=mock_file
        - MAIL_PIC_API_ROOT_URL=https://mock_url/mail/api/xgemail
        - INTERNET_SUBMIT_BUCKET=sandbox-cloudemail-xgemail-submit
        - INTERNET_SUBMIT_STORAGE_ROOT=s3://sandbox-cloudemail-xgemail-submit
        - CUSTOMER_SUBMIT_STORAGE_ROOT=http://localstack:4576/s3/some-policy/path
        - SAVI_HOST_NAME=localhost
        - SAVI_PORT=4010
        - MALWARE_SERVICE_ENABLED=false
        - CONTENT_FILTERING_ENABLED=false
        - INTERNET_SUBMIT_SERVICE_QUEUE=vpc-000000-sandbox-Internet_Submit_Service_Queue
        - POLICY_BUCKET=sandbox-cloudemail-xgemail-policy
        - POLICY_STORAGE_ROOT=s3://sandbox-cloudemail-xgemail-policy
        - MAILBOX_LOCAL_PART_FILE_PATH=config/policies/domains/
        - MAILBOX_POLICY_FILE_PATH=config/policies/endpoints/
        - SQS_ENDPOINT=http://localstack:4576
        - S3_ENDPOINT=http://localstack:4572
        - SNS_ENDPOINT=http://localstack:4575
      networks:
        - novanet

  postfix-is:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:latest
    container_name: postfix-is
    hostname: internet-submit
    domainname: local.sandbox.hydra.sophos.com
    ports:
      - '5225:25' #SMTP
    environment:
      - HOSTNAME_EXTERNAL=internet-submit
      - INSTANCE_TYPE=internet-submit
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
    depends_on:
      - jilter-inbound
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
    networks:
      - novanet

  postfix-cd:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:latest
    container_name: postfix-cd
    hostname: customer-delivery
    domainname: local.sandbox.hydra.sophos.com
    environment:
      - HOSTNAME_EXTERNAL=customer-delivery
      - INSTANCE_TYPE=customer-delivery
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
      - DEBUG=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
    networks:
      - novanet

  # postfix-xd:
  #   image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:latest
  #   container_name: postfix-xd
  #   hostname: extended-delivery
  #   domainname: local.sandbox.hydra.sophos.com
  #   environment:
  #     - HOSTNAME_EXTERNAL=extended-delivery
  #     - INSTANCE_TYPE=xdelivery
  #     - DEFAULT_REGION=local
  #     - DEFAULT_ENVIRONMENT=sandbox
  #   volumes:
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #     - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
  #   networks:
  #     - novanet

  jilter-inbound:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/jilter-common:latest
    container_name: jilter-inbound
    hostname: jilter-inbound
    domainname: sandbox.sophos
    environment:
      - JILTER_VERSION=current
      - DIRECTION=inbound
      - HOSTNAME_EXTERNAL=jilter-inbound
      - INSTANCE_TYPE=jilter-inbound
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
      - APPLICATION=
    ports:
      - '9876:9876'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
      - ~/.xgemail_sandbox/jilter/inbound/:/jilter/
      - ~/.xgemail_sandbox/policy_storage://policy-storage:rw
    networks:
      - novanet

  sasi-service-inbound:
    image: email/sasi-service
    container_name: sasi-service-inbound
    hostname: sasi-service-inbound
    domainname: sandbox.sophos
    extra_hosts:
      - "sasi-daemon:172.16.199.111"
    external_links:
      - 'dynamodb:dynamo-service'
    environment:
      - aws.accessKeyId=$AWS_ACCESS_KEY_ID
      - aws.secretKey=$AWS_SECRET_ACCESS_KEY
      - logging.level.com.sophos=INFO
      - APPLICATION_NAME=sasi-inbound
      - COUNTER_DB_TABLE=None
      - enableLabsMonitoring=false
      - HISTORIAN_DB_TABLE=None
      - HISTORIAN_DB_TABLE_CREATE_DATE=None
      - SASI_REQUEST_QUEUE=sandbox-SASI_Request
      - SASI_RESPONSE_QUEUE=sandbox-SASI_Response
    volumes:
      - $XGEMAIL_HOME/xgemail-infrastructure/orchestrator/sasi/inbound-application.properties:/application.properties
    ports:
      - '18082:8080'
    depends_on:
      - "sasi-daemon"
    networks:
      - novanet

networks:
  novanet:
    external:
      name: nova_novanet
