version: '3'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4567:4567' #API Gateway
      - '4568:4568' #Kinesis
      - '4569:4569' #DynamoDB
      - '4570:4570' #DynamoDB Streams
      - '4571:4571' #ElasticSearch
      - '4572:4572' #S3
      - '4574:4574' #Lambda
      - '4575:4575' #SNS
      - '4576:4576' #SQS
      - '4578:4578' #Elasticsearch Service
      - '8081:8081' #WebUI
    environment:
      - PORT_WEB_UI=8081
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=apigateway,kinesis,dynamodb,dynamodbstreams,s3,sns,sqs,es,lambda
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack
    networks:
      - novanet

#  sasi-service:
#    image: email/sasi-service
#    container_name: sasi-service
#    hostname: sasi-service
#    domainname: sandbox.sophos
#    env_file:
#      - ~/.aws/credentials
#    ports:
#      - '8080:8080'
#    depends_on:
#      - "sasi-daemon"
#    networks:
#      - novanet
#
#  sasi-daemon:
#    image: email/sasi-daemon
#    container_name: sasi-daemon-contanier
#    hostname: sasi-daemon
#    domainname: sandbox.sophos
#    ports:
#      - '32223:32223'
#    networks:
#      - novanet

  mail:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/sophos_cloud_tomcat:latest
    container_name: mail-service
    hostname: mail-service
    domainname: sandbox.sophos
    ports:
      - '9898:8080'
    networks:
      - novanet
    dns:
      - 172.16.199.101
    external_links:
      - 'postgres:postgres-service'
      - 'mongo:mongo-service'
      - 'memcache:memcache-service'
      - 'redis:redis-service'
      - 'kinesalite:kinesalite'
      - 'dynamodb:dynamo-service'
      - 'elasticmq:elasticmq-service'
      - 'elasticsearch:elasticsearch-service'
      - 'mailcatcher:mailcatcher-service'
    volumes:
      - $XGEMAIL_HOME/xgemail-infrastructure/orchestrator/sophos_cloud_tomcat_bootstrap.properties:/usr/local/etc/sophos/bootstrap.properties

networks:
  novanet:
    external:
      name: nova_novanet