version: "3"
services:
  localstack-xgemail:
    image: localstack/localstack
    container_name: localstack-xgemail
    ports:
      - '4567:4567' #API Gateway
      - '4568:4568' #Kinesis
      - '4569:4569' #DynamoDB
      - '4570:4570' #DynamoDB Streams
      - '4571:4571' #ElasticSearch
      - '4572:4572' #S3
      - '4574:4574' #Lambda
      - '4575:4575' #SNS
      - '4576:4576' #SQS
      - '4578:4578' #Elasticsearch Service
      - '8081:8081' #WebUI
    environment:
      - PORT_WEB_UI=8081
      - HOSTNAME_EXTERNAL=localstack-xgemail
      - SERVICES=apigateway,kinesis,dynamodb,dynamodbstreams,s3,sns,sqs,es,lambda
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack
    networks:
      - novanet

  cyren:
      image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/cyren:latest
      container_name: cyren
      hostname: cyren
      domainname: sandbox.sophos
      ports:
        - '8088:8088' #cyren port
      networks:
        - novanet

  savi:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/savi:latest
    container_name: savi
    hostname: savi
    domainname: sandbox.sophos
    ports:
      - '4010:4010'
    networks:
      - novanet

  postfix-is:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:1.0.0
    container_name: postfix-is
    hostname: internet-submit
    domainname: local.sandbox.hydra.sophos.com
    ports:
      - '5225:25' #SMTP
    environment:
      - HOSTNAME_EXTERNAL=internet-submit
      - INSTANCE_TYPE=submit
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
    networks:
      - novanet

  postfix-cs:
      image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:1.0.0
      container_name: postfix-cs
      hostname: customer-submit
      domainname: local.sandbox.hydra.sophos.com
      ports:
        - '5125:25' #SMTP
      environment:
        - HOSTNAME_EXTERNAL=customer-submit
        - INSTANCE_TYPE=customer-submit
        - DEFAULT_REGION=local
        - DEFAULT_ENVIRONMENT=sandbox
        - DEBUG=1
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
      networks:
        - novanet

  postfix-cd:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:1.0.0
    container_name: postfix-cd
    hostname: customer-delivery
    domainname: local.sandbox.hydra.sophos.com
    ports:
      - '5025:25' #SMTP
    environment:
      - HOSTNAME_EXTERNAL=customer-delivery
      - INSTANCE_TYPE=customer-delivery
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
      - DEBUG=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
    networks:
      - novanet

  jilter-inbound:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/jilter-inbound:latest
    container_name: jilter-inbound
    hostname: jilter-inbound
    domainname: sandbox.sophos
    environment:
      - JILTER_VERSION=0.7.9-SNAPSHOT
    ports:
      - '9876:9876'
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail/xgemail-jilter-inbound/build/distributions:/jilter
      - ~/.policy-storage:/policy-storage:rw
    networks:
      - novanet

  jilter-outbound:
      image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/jilter-outbound:latest
      container_name: jilter-outbound
      hostname: jilter-outbound
      domainname: sandbox.sophos
      environment:
        - JILTER_VERSION=0.4.6-SNAPSHOT
      ports:
        - '19876:9876'
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
        - $XGEMAIL_HOME/xgemail/xgemail-jilter-outbound/build/distributions:/jilter
        - ~/.policy-storage:/policy-storage:rw
      networks:
        - novanet

  postfix-xd:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:1.0.0
    container_name: postfix-xd
    hostname: extended-delivery
    domainname: local.sandbox.hydra.sophos.com
    environment:
      - HOSTNAME_EXTERNAL=extended-delivery
      - INSTANCE_TYPE=xdelivery
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
    networks:
      - novanet

  postfix-ix:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:1.0.0
    container_name: postfix-ix
    hostname: internet-xdelivery
    domainname: local.sandbox.hydra.sophos.com
    environment:
      - HOSTNAME_EXTERNAL=internet-xdelivery
      - INSTANCE_TYPE=internet-xdelivery
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - $XGEMAIL_HOME/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
    networks:
      - novanet


networks:
  novanet:
    external:
      name: nova_novanet
