---
# Copy AMI to Destination Regions
# http://docs.ansible.com/ansible/latest/ec2_ami_copy_module.html
- name: "Copy AMI to Destination Regions {{ami.xgemail.ami_destination_regions}}"
  async: 600
  poll: 0
  ec2_ami_copy:
    description:          "{{ec2_ami_output.description}}"
    source_region:        "{{ami.xgemail.region}}"
    region:               "{{item}}"
    source_image_id:      "{{ec2_ami_output.image_id}}"
    name:                 "{{ec2_ami_output.name}}"
    tags:                 "{{ec2_ami_output.tags}}"
    wait:                 no
  with_items:             "{{ami.xgemail.ami_destination_regions}}"
  register: ec2_ami_copy_output

- name: "Display Xgemail AMI Copy Output"
  debug:
    msg: "{{ec2_ami_copy_output}}"
    verbosity: 3

- name: "Display Xgemail AMI IDs and their Region"
  debug:
    msg: "AMI {{item.image_id}} copied in {{item.item}}"
  with_items: "{{ec2_ami_copy_output}}"
  changed_when: false

- name: "EC2 AMI Copy Result Poll."
  async_status:
    jid: "{{item.ansible_job_id}}"
  with_items: "{{ec2_ami_copy_output.results}}"
  register: ec2_ami_copy_poll_results
  until: "{{ec2_ami_copy_poll_results.finished}}"
  delay: 10
  retries: 300

#- name: "Display Xgemail AMI Copy Output"
#  debug:
#    msg: "{{ec2_ami_copy_output}}"
#    verbosity: 3
#


#- name: "Write info to Region-Ami.txt "
#  lineinfile:
#    dest: "{{ playbook_dir }}/Region-Ami.txt"
#    regexp: "^{{ item.key }}"
#    line: "{{ item.key }}: {{ '\"' + item.value + '\"' }}"
#  with_items:
#    - { key: 'aws_region', value: "{{ ec2_ami_copy_output.results[0].item }}" }
#    - { key: 'AMI-ID', value: "{{ ec2_ami_copy_output.results[0].image_id }}" }
#    - { key: 'aws_region', value: "{{ ec2_ami_copy_output.results[1].item }}" }
#    - { key: 'AMI-ID', value: "{{ ec2_ami_copy_output.results[1].image_id }}" }
#    - { key: 'aws_region', value: "{{ ec2_ami_copy_output.results[2].item }}" }
#    - { key: 'AMI-ID', value: "{{ ec2_ami_copy_output.results[2].image_id }}" }

#- name: "EC2 AMI Update Launch Permissions on newly copied Images in regions {{ami.xgemail.ami_destination_regions}}"
#  async: 600
#  poll: 0
#  ec2_ami:
#    image_id: "{{ item.image_id }}"
#    region: "{{item.invocation.module_args.region}}"
#    state: present
#    wait: no
#    launch_permissions:
#      user_ids: "{{ami.xgemail.ami_launch_permissions}}"
#  with_items: "{{ec2_ami_copy_poll_results.results}}"
#  register: ec2_ami_permissions_output
#
#- name: "EC2 AMI Update Launch Permissions Result Check."
#  async_status:
#    jid: "{{item.ansible_job_id}}"
#  with_items: "{{ec2_ami_permissions_output.results}}"
#  register: ec2_ami_permissions_poll_results
#  until: "{{ec2_ami_permissions_poll_results.finished}}"
#  retries: 30
#

- name: "EC2 AMI Update Launch Permissions on newly copied Images."
  ec2_ami:
    name: "{{ec2_ami_output.name}}"
    image_id: "{{ item.image_id }}"
    region: "{{item.item}}"
    state: present
    launch_permissions:
      user_ids: "{{ami.xgemail.ami_launch_permissions}}"
  ignore_errors: yes
  with_items: "{{ec2_ami_copy_output}}"
  register: ec2_ami_permissions_output
