---
# Tagged AMI copy
- ec2_ami_copy:
description:
    source_region: us-east-1
    region: eu-west-1
    source_image_id: ami-xxxxxxx
    name:
    tags:
        Name: My-Super-AMI
        Branch: "{{build.branch}}"
        Build: "{{build.number}}"