---
# Copy AMI to Destination Regions
# http://docs.ansible.com/ansible/latest/ec2_ami_copy_module.html
- name: Regions for release, bugfix, and hotfix branches
  set_fact:
    branch_destination_regions: [ 'us-east-2', 'eu-west-1', 'eu-central-1', 'ca-central-1', 'ap-northeast-1', 'ap-southeast-2', 'ap-south-1', 'sa-east-1' ]

- name: Regions for feature branches
  set_fact:
    branch_destination_regions: [ 'us-east-2', 'eu-west-1' ]
  when: build.branch | regex_search('feature')

- name: Regions for develop branch
  set_fact:
    branch_destination_regions: [ 'us-east-2', 'eu-west-1', 'ca-central-1' ]
  when: build.branch | regex_search('develop')

- name: "Update AWS Software"
  shell: pip install awscli botocore boto3 -U
  register: update_output
  until: update_output.stdout|length
  delay: 10
  retries: 3

- name: "Copy AMI to Destination Regions {{branch_destination_regions}}"
  ec2_ami_copy:
    description:          "{{image_description}}"
    source_region:        "{{ami.xgemail.region}}"
    region:               "{{item}}"
    source_image_id:      "{{image_id}}"
    name:                 "{{image_name}}"
    tags:
      Name:         "{{image_name}}"
      branch:       "{{ami.xgemail.branch}}"
      build:        "{{ami.xgemail.build}}"
      build_id:     "{{ami.xgemail.build_id}}"
      ami_type:     xgemail
    wait:                 true
    wait_timeout:         1200
    launch_permissions:
      user_ids: "{{ami.xgemail.ami_launch_permissions}}"
  with_items:             "{{branch_destination_regions}}"
  register: ec2_ami_copy_output

- name: "Display Xgemail AMI IDs and their Region"
  debug:
    msg: "AMI {{item.image_id}} copied in {{item.item}}"
  with_items: "{{ec2_ami_copy_output.results}}"
  changed_when: false

- name: "Write info to Region-Ami.txt "
  lineinfile:
    dest: "{{playbook_dir}}/Region-Ami.txt"
    line: "{{item}}"
    state: present
    create: yes
  with_items:
    - "Region: {{ami.xgemail.region}} AmiId: {{image_id}}"
    #- "Region: {{ec2_ami_copy_output.results[0].item}} AmiId: {{ec2_ami_copy_output.results[0].image_id}}"
    #- "Region: {{ec2_ami_copy_output.results[1].item}} AmiId: {{ec2_ami_copy_output.results[1].image_id}}"
    #- "Region: {{ec2_ami_copy_output.results[2].item}} AmiId: {{ec2_ami_copy_output.results[2].image_id}}"

#- name: "EC2 AMI Update Launch Permissions on newly copied Images in regions {{ami.xgemail.ami_destination_regions}}"
#  ec2_ami:
#    name: "{{ec2_ami_output.name}}"
#    tags: "{{ec2_ami_output.tags}}"
#    image_id: "{{ item.image_id }}"
#    region: "{{item.item}}"
#    state: present
#    launch_permissions:
#      user_ids: "{{ami.xgemail.ami_launch_permissions}}"
#  with_items: "{{ec2_ami_copy_output.results}}"
#  register: ec2_ami_permissions_output
