---
# Copy AMI to Destination Regions
- name: "Copy AMI to Destination Regions {{ami.xgemail.ami_destination_regions}}"
  async: 600
  poll: 0
  ec2_ami_copy:
    description:          "{{xgemail_ami.results[0].description}}"
    source_region:        "{{ami.xgemail.region}}"
    region:               "{{item}}"
    source_image_id:      "{{xgemail_ami.results[0].image_id}}"
    name:                 "{{xgemail_ami.results[0].name}}"
    tags:                 "{{xgemail_ami.results[0].tags}}"
    wait:                 no
  with_items:             "{{ami.xgemail.ami_destination_regions}}"
  register: ec2_ami_copy_output

- async_status:
    jid: "{{item.ansible_job_id}}"
  with_items: "{{ec2_ami_copy_output.results}}"
  register: ec2_ami_copy_poll_results
  until: "{{ec2_ami_copy_poll_results.finished}}"
  retries: 30

- name: "Set Fact xgemail_ami"
  set_fact:
    ec2_ami_image_id: "{{ xgemail_ami.results[0].image_id }}"
    when: ec2_ami_copy_output.failed != true

- name: "Display Xgemail AMI Id"
  debug:
    msg: "{{ec2_ami_copy_output.results[0].image_id}}"
    when: ec2_ami_copy_output.failed != true

- debug:
    var: ec2_ami_copy_output.results[0]
    verbosity: 3
    when: ec2_ami_copy_output.failed != true

- name: "Display Xgemail AMI Find Output"
  debug:
    msg: "{{ec2_ami_copy_output}}"
    verbosity: 3
    when: ec2_ami_copy_output.failed != true