---
# http://docs.ansible.com/ansible/latest/cloudformation_module.html
- name: "Deploy Xgemail AMI Stack to {{ami.xgemail.environment}} {{account.region}}"
  cloudformation:
    stack_name: "{{ami.xgemail.stack_name}}"
    state: "present"
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{role_path}}/files/cf_templates/image_xgemail_template.json"
    template_parameters:
      AesDecryptionKey:            "{{ami.xgemail.aes_decryption_key}}"
      AmiBuildTimeoutMinutes:      "{{ami.xgemail.ami_build_timeout_minutes}}"
      ApplicationName:             "{{ami.xgemail.application_name}}"
      Branch:                      "{{ami.xgemail.branch}}"
      Build:                       "{{ami.xgemail.build}}"
      Environment:                 "{{ami.xgemail.environment}}"
      IamProfile:                  "{{ami.xgemail.iam_profile}}"
      ImageId:                     "{{ec2_ami_image_id}}"
      InstanceType:                "{{ami.xgemail.instance_type}}"
      JdkVersion:                  "{{ami.xgemail.jdk_version}}"
      JilterInboundVersion:        "{{ami.xgemail.jilter_inbound_version}}"
      JilterOutboundVersion:       "{{ami.xgemail.jilter_outbound_version}}"
      JilterMfInboundVersion:      "{{ami.xgemail.jilter_mf_inbound_version}}"
      JilterMfOutboundVersion:     "{{ami.xgemail.jilter_mf_outbound_version}}"
      JilterEncryptionVersion:     "{{ami.xgemail.jilter_encryption_version}}"
      JilterDeliveryVersion:       "{{ami.xgemail.jilter_delivery_version}}"
      LaunchDarklyInf:             "{{ami.xgemail.launch_darkly_inf}}"
      LaunchDarklyDev:             "{{ami.xgemail.launch_darkly_dev}}"
      LaunchDarklyDev3:            "{{ami.xgemail.launch_darkly_dev3}}"
      LaunchDarklyQa:              "{{ami.xgemail.launch_darkly_qa}}"
      LaunchDarklyProd:            "{{ami.xgemail.launch_darkly_prod}}"
      S3CookbookRepositoryUrl:     "{{ami.xgemail.s3_cookbook_repository_url}}"
      VpcSecurityGroup:            "{{ami.xgemail.vpc_security_group}}"
      VpcSubnetId:                 "{{ami.xgemail.vpc_subnet_id}}"
  register: ami_stack_output

- name: "Display EC2 Instance Id"
  debug:
    msg: "{{ami_stack_output.stack_outputs.InstanceId}}"

- debug:
    var: ami_stack_output
    verbosity: 3

- name: "Display AMI Stack Output"
  debug:
    msg: "{{ami_stack_output.stack_outputs}}"
    verbosity: 2

- lineinfile:
    path: "{{playbook_dir}}/instance_id.ini"
    line: 'instance_id={{ami_stack_output.stack_outputs.InstanceId}}'
    state: present
    create: yes
