---
# Xgemail AMI Creation
- ec2_ami:
    description: "Sophos, Inc. Prepared image of {{build.branch}}-{{ami.xgemail.application_name}}-{{build.number}}"
    instance_id: "{{ami_stack.stack_outputs.InstanceId}}"
    state: present
    region: "{{ami.xgemail.region}}"
    wait: yes
    wait_timeout:
    name: "{{account.name}}-{{build.branch}}-{{app.name}}-{{build.number}}-{{ansible_date_time.epoch}}"
    launch_permissions: "{{ami.xgemail.ami_launch_permissions}}"
    tags:
      Name:         "{{account.name}}-{{build.branch}}-{{ami.xgemail.application_name}}-{{build.number}}-{{ansible_date_time.epoch}}"
      Branch:       "{{ami.xgemail.branch}}"
      Branch:       "{{ami.xgemail.build}}"
  register: xgemail_ami

- name: "Set Fact xgemail_ami"
  set_fact:
    ec2_ami_image_id: "{{ xgemail_ami.results[0].image_id }}"
    when: xgemail_ami.failed != true

- name: "Display Xgemail AMI Id"
  debug:
    msg: "{{xgemail_ami.results[0].image_id}}"
    when: xgemail_ami.failed != true

- debug:
    var: xgemail_ami.results[0]
    verbosity: 3
    when: xgemail_ami.failed != true

- name: "Display Xgemail AMI Find Output"
  debug:
    msg: "{{xgemail_ami}}"
    verbosity: 3
    when: xgemail_ami.failed != true