---
- name: "Download Xgemail AMI Creation logs for {{xgemail_ami.results[0].ami_id}}"
  s3:
    mode:               get
    region:             "{{account.region}}"
    bucket:             "{{ami.xgemail.ami_bucket}}"
    object:             "{{build.branch}}/build-{{build.number}}/create-{{ami.xgemail.application_name}}-ami-b{{build.number}}.zip"
    dest:               "{{playbook_dir}}"
    overwrite:          always