---
- name: "Download Xgemail AMI Creation the config file for {{stack.iam.cloud_email_roles}} to the config bucket {{cloud_applications}}"
  s3:
    mode:               put
    region:             "{{account.region}}"
    bucket:             "{{cloud_applications}}"
    object:             "{{build.branch}}/roles_xgemail_template.json"
    src:                "{{template.iam.roles_xgemail_template}}"
    overwrite:          always