---
- name: "Download Xgemail AMI Creation logs for {{ami.xgemail.stack_name}}"
  aws_s3:
    mode:                         get
    ignore_nonexistent_bucket:    True
    region:                       "{{account.region}}"
    bucket:                       "{{ami.xgemail.ami_bucket}}"
    object:                       "{{build.branch}}/build-{{build.number}}/create-{{ami.xgemail.application_name}}-ami-b{{build.number}}.zip"
    dest:                         "{{playbook_dir}}"
    overwrite:                    always