---
- name: "Get Console Output from AMI EC2 Instance"
  shell: aws ec2 get-console-output --instance-id {{ami_stack_output.stack_resources[0].physical_resource_id}} --region us-west-2 --output text
  register: console_output
  until: console_output.stdout|length
  delay: 10
  retries: 3

- name: "Print Console Output."
  debug:
    var: console_output