az:
  a: us-west-2a
  b: us-west-2b
  c: us-west-2c

aws:
  asg:
    cd:
      as_min_size:                              "9"
      as_max_size:                              "12"
    is:
      as_min_size:                              "12"
      as_max_size:                              "18"