az:
  a: us-west-2a
  b: us-west-2b
  c: us-west-2c

aws:
  asg:
    cd:
      as_min_size:                              "21"
      as_max_size:                              "50"
      cron_scale_in:                            "00 02 * * 1-5"
      cron_scale_out:                           "45 12 * * 1-5"
      on_hour_desired:                          "27"
      scale_in_out_weekdays:                    "true"
    cs:
      cron_scale_in:                            "00 02 * * 1-5"
      cron_scale_out:                           "30 14 * * 1-5"
      off_hour_desired:                         "3"
      on_hour_desired:                          "2"
      scale_in_out_weekdays:                    "false"
    is:
      as_min_size:                              "21"
      as_max_size:                              "50"
      cron_scale_in:                            "00 02 * * 1-5"
      cron_scale_out:                           "30 14 * * 1-5"
      on_hour_desired:                          "27"
      scale_in_out_weekdays:                    "true"
    mfis:
      as_min_size:                              "3"
      as_max_size:                              "6"
      instance_size:                            "m5a.2xlarge"
      on_hour_desired:                          "6"
    mfos:
      as_min_size:                              "3"
      as_max_size:                              "6"
      instance_size:                            "m5a.2xlarge"
      on_hour_desired:                          "6"
  efs:
    policy_efs_volume:
      provisioned_throughput_in_mibps:          "10"
      throughput_mode:                          "provisioned"
