- name: "Deploy {{stack.ec2.asg.bastion}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.ec2.asg.bastion}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.ec2.asg.bastion}}"
    template_parameters:
      AmiId:                                "{{ami_id}}"
      AutoScalingMinSize:                   "{{as_min_cap_bastion}}"
      AvailabilityZones:                    "{{cloud_email_vpc_stack.stack_outputs.AvailabilityZones}}"
      BastionInstanceProfile:               "{{iam_stack.stack_outputs.BastionInstanceProfile}}"
      BastionSecurityGroup:                 "{{sg_stack.stack_outputs.SecurityGroupBastion}}"
      Branch:                               "{{build.branch}}"
      Environment:                          "{{account.name}}"
      KeyName:                              "bastion-{{account.region}}"
      LogstashServer:                       "lgstshshipper.{{vpc.cloud_email.name|lower}}.{{account.region}}.{{account.name}}.{{cloudstation_hostedzone}}:5000"
      ScaleDownOnWeekends:                  "false"
      ScaleDownCron:                        "{{cron_scale_down}}"
      ScaleUpCron:                          "{{cron_scale_up}}"
      Vpc:                                  "{{cloud_email_vpc_stack.stack_outputs.Vpc}}"
      VpcName:                              "{{vpc.cloud_email.name}}"
      VpcZoneIdentifiers:                   "{{cloud_email_vpc_stack.stack_outputs.VpcZoneIdentifiersPublic}}"
  register: bastion_stack

- debug:
    var: bastion_stack
    verbosity: 3

- name: "Display CloudEmail Bastion Stack Output"
  debug:
    msg: "{{bastion_stack.stack_outputs}}"
    verbosity: 2