---
- name: "Deploy {{stack.vpc.cloud_email_vpc}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name: "{{stack.vpc.cloud_email_vpc}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    stack_policy: "{{tmp_artifacts_dir}}/vpc_policy.json"
    template: "{{template.vpc.vpc_template}}"
    template_parameters:
      Environment:              "{{account.name}}"
      AZs:                      "{{account.region}}a, {{account.region}}b, {{account.region}}c"
  register: cloud_email_vpc_stack

- debug:
    var: cloud_email_vpc_stack
    verbosity: 3

- name: "Display VPC Stack Output"
  debug:
    msg: "{{cloud_email_vpc_stack.stack_outputs}}"
    verbosity: 2