---
# ToC Elasticsearch Cluster
- name: "Deploy ToC Elasticsearch Domains {{stack.es.toc_elasticsearch_domain}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.es.toc_elasticsearch_domain}}"
    state:                        "{{aws.es.toc_elasticsearch_domain.state}}"
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.es.es_domain_template}}"
    template_parameters:
      EbsVolumeSize:              "{{aws.es.toc_elasticsearch_domain.ebs_volume_size}}"
      ElasticsearchVersion:       "{{aws.es.toc_elasticsearch_domain.es_version}}"
      Environment:                "{{account.name}}"
      EsName:                     "{{aws.es.toc_elasticsearch_domain.es_name}}"
      HopperIpAccess:             "{{hopper_public_ip}}"
      HostedZoneName:             "{{hostedzone}}."
      MasterNodeType:             "{{aws.es.toc_elasticsearch_domain.master_node_type}}"
      NodeType:                   "{{aws.es.toc_elasticsearch_domain.node_type}}"
      NumberOfInstances:          "{{aws.es.toc_elasticsearch_domain.instance_number}}"
      NumberOfMasterInstances:    "{{aws.es.toc_elasticsearch_domain.master_instance_number}}"
      SnapshotStartHour:          "{{aws.es.toc_elasticsearch_domain.snapshot_start_hour}}"
      VpcNameLowerCase:           "{{vpc.cloud_email.name|lower}}"
      ZoneAwareness:              "{{aws.es.toc_elasticsearch_domain.zone_awareness}}"
  register: toc_es_stack

- debug:
    var: toc_es_stack
    verbosity: 3

- name: "Display ToC Elasticsearch Domain Stack Output"
  debug:
    msg: "{{toc_es_stack.stack_outputs}}"
    verbosity: 2