---
# CloudEmail Elasticsearch Cluster
- name: "Deploy CloudEmail Elasticsearch Domains {{stack.es.xgemail_elasticsearch_domain}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.es.xgemail_elasticsearch_domain}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.es.es_domain_template}}"
    template_parameters:
      EbsVolumeSize:              "{{aws.es.xgemail_elasticsearch_domain.ebs_volume_size}}"
      ElasticsearchVersion:       "{{aws.es.xgemail_elasticsearch_domain.es_version}}"
      EncryptionAtRest:           "{{aws.es.xgemail_elasticsearch_domain.encryption_at_rest}}"
      Environment:                "{{account.name}}"
      EsName:                     "{{aws.es.xgemail_elasticsearch_domain.es_name}}"
      HopperIpAccess:             "{{hopper_public_ip}}"
      HostedZoneName:             "{{hostedzone}}."
      KmsKeyId:                   "{{storage_kms_key_id}}"
      MasterNodeType:             "{{aws.es.xgemail_elasticsearch_domain.master_node_type}}"
      NodeType:                   "{{aws.es.xgemail_elasticsearch_domain.node_type}}"
      NumberOfInstances:          "{{aws.es.xgemail_elasticsearch_domain.instance_number}}"
      NumberOfMasterInstances:    "{{aws.es.xgemail_elasticsearch_domain.master_instance_number}}"
      SnapshotStartHour:          "{{aws.es.xgemail_elasticsearch_domain.snapshot_start_hour}}"
      VpcNameLowerCase:           "{{vpc.cloud_email.name|lower}}"
      ZoneAwareness:              "{{aws.es.xgemail_elasticsearch_domain.zone_awareness}}"
  register: xgemail_es_stack

- debug:
    var: xgemail_es_stack
    verbosity: 3

- name: "Display CloudEmail Elasticsearch Domain Stack Output"
  debug:
    msg: "{{xgemail_es_stack.stack_outputs}}"
    verbosity: 2

# Enable AWS Elasticsearch Logging to CloudWatch
vars:
  policy_document:
      Version: 2012-10-17
      Statement:
        -
          Sid: ElasticsearchToCloudWatchErrorLogs
          Effect: Allow
          Principal:
            Service: es.amazonaws.com
          Action:
            - logs:PutLogEvents
            - logs:PutLogEventsBatch
            - logs:CreateLogStream
          Resource: "{{xgemail_es_stack.stack_outputs.CloudWatchErrorLogsArn}}"

- name: "Grant Amazon Elasticsearch permissions to write to the ErrorLog log group"
  command: >
    aws logs put-resource-policy
      --policy-name
      --policy-document {{policy_document | to_json }}
  register: es_cw_error_log_policy

- name: "Enable Amazon Elasticsearch logging to ErrorLog log group"
  command: >
    aws es update-elasticsearch-domain-config
      --domain-name "{{xgemail_es_stack.stack_outputs.ElasticSearchDomain}}"
      --log-publishing-options
      \"ES_APPLICATION_LOGS={CloudWatchLogsLogGroupArn={{xgemail_es_stack.stack_outputs.CloudWatchErrorLogsArn}},Enabled=true}\"
  register: es_update_log_config

# ToC Elasticsearch Cluster
- name: "Deploy ToC Elasticsearch Domains {{stack.es.toc_elasticsearch_domain}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.es.toc_elasticsearch_domain}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.es.es_domain_template}}"
    template_parameters:
      EbsVolumeSize:              "{{aws.es.toc_elasticsearch_domain.ebs_volume_size}}"
      ElasticsearchVersion:       "{{aws.es.toc_elasticsearch_domain.es_version}}"
      Environment:                "{{account.name}}"
      EsName:                     "{{aws.es.toc_elasticsearch_domain.es_name}}"
      HopperIpAccess:             "{{hopper_public_ip}}"
      HostedZoneName:             "{{hostedzone}}."
      MasterNodeType:             "{{aws.es.toc_elasticsearch_domain.master_node_type}}"
      NodeType:                   "{{aws.es.toc_elasticsearch_domain.node_type}}"
      NumberOfInstances:          "{{aws.es.toc_elasticsearch_domain.instance_number}}"
      NumberOfMasterInstances:    "{{aws.es.toc_elasticsearch_domain.master_instance_number}}"
      SnapshotStartHour:          "{{aws.es.toc_elasticsearch_domain.snapshot_start_hour}}"
      VpcNameLowerCase:           "{{vpc.cloud_email.name|lower}}"
      ZoneAwareness:              "{{aws.es.toc_elasticsearch_domain.zone_awareness}}"
  register: toc_es_stack

- debug:
    var: toc_es_stack
    verbosity: 3

- name: "Display ToC Elasticsearch Domain Stack Output"
  debug:
    msg: "{{toc_es_stack.stack_outputs}}"
    verbosity: 2