---
# Upload Files
# Documentation: http://ansible-manual.readthedocs.io/en/latest/s3_module.html
- name: "Upload the config file for {{stack.ec2.sg.cloud_email_security_groups}} to the config bucket {{cloud_applications}}"
  s3:
    mode:               put
    region:             "{{account.region}}"
    bucket:             "{{cloud_applications}}"
    object:             "{{build.branch}}/xgemail-infrastructure/{{template.ec2.sg.sg_xgemail_template}}"
    src:                "{{template.ec2.sg.sg_xgemail_template}}"
    overwrite:          always

- name: "Deploy Security Groups {{stack.ec2.sg.cloud_email_security_groups}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:              "{{stack.ec2.sg.cloud_email_security_groups}}"
    state:                   present
    region:                  "{{account.region}}"
    disable_rollback:        true
    template_url:            "https://s3.amazonaws.com/{{cloud_applications}}/{{build.branch}}/xgemail-infrastructure/{{template.ec2.sg.sg_xgemail_template}}"
    template_parameters:
      Branch:                "{{build.branch}}"
      Environment:           "{{account.name}}"
      ExternalIpAccessList:  "{{external_ip_access.office.bur.a}}, {{external_ip_access.office.bur.b}}, {{external_ip_access.office.bur.c}}, {{external_ip_access.office.bur.d}}, {{external_ip_access.office.bur.e}}"
      HopperIpAccessA:       "{{external_ip_access.hopper.a}}"
      HopperIpAccessB:       "{{external_ip_access.hopper.b}}"
      HopperIpAccessC:       "{{external_ip_access.hopper.c}}"
      Vpc:                   "{{cloud_email_vpc_stack.stack_outputs.Vpc}}"
  register: sg_stack

- debug:
    var: sg_stack
    verbosity: 3

- name: "Display Security Groups Stack Output"
  debug:
    msg: "{{sg_stack.stack_outputs}}"
    verbosity: 2