---
- name: "Get Spot Instance price for {{instance_size_bastion}} in {{account.region}}"
  ec2_spot_pricing_history_facts:
    instance_types: ["{{instance_size_bastion}}"]
    region: "{{account.region}}"
    availability_zone: "{{account.region}}a"
    product_descriptions: ["Linux/UNIX (Amazon VPC)"]
    max_results: 1
  register: ec2_spot_pricing_output

- debug:
    var: ec2_spot_pricing_output
    verbosity: 3

- name: "Display Spot Instance Price"
  debug:
    msg: "{{ec2_spot_pricing_output.ec2_spot_pricing_history[0].spot_price}}"
    verbosity: 2

- name: Set Spot Price
  set_fact:
    spot_price: "{{ec2_spot_pricing_output.ec2_spot_pricing_history[0].spot_price}}"