---
- name: Debug
  debug:
    msg: "{{item.value.stack_name}} {{item.value.template}} {{item.value.template_parameters}}"
  with_dict: "{{aws.sqs}}"

- name: "Create SQS Queue Stacks in AWS"
  async: 200
  poll: 0
  cloudformation:
    stack_name:           "{{item.value.stack_name}}"
    state:                "{{item.value.state}}"
    region:               "{{account.region}}"
    disable_rollback:     true
    template:             "{{item.value.template}}"
    template_parameters:  "{{item.value.template_parameters}}"
  with_dict:              "{{aws.sqs}}"
  register:               sqs_stack_async_results

- async_status:
    jid:                  "{{item.ansible_job_id}}"
  with_items:             "{{sqs_stack_async_results.results}}"
  register:               sqs_stack_async_poll_results
  until:                  "{{sqs_stack_async_poll_results.finished}}"
  retries:                30