---
- name: "Deploy client ids SSM parameters"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_wsr_client_ids}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_wsr_param_template}}"
    template_parameters:
      Key:                        "xgemail.white.space.remove.from.header.client.ids"
      Value:                      "id1,id2"
  register: ssm_stack

- name: "Deploy client region SSM parameters to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_wsr_regions}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_wsr_param_template}}"
    template_parameters:
      Key:                        "xgemail.white.space.remove.from.header.aws.regions"
      Value:                      "NA"
  register: ssm_stack
