---
- name: "Deploy client ids SSM parameters"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_wsr_client_ids}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_wsr_param_template}}"
    template_parameters:
      Key:                        "{{aws.ssm.white_space_remove_from_header_client_ids_key}}"
      Value:                      "{{aws.ssm.white_space_remove_from_header_client_ids}}"
  register: ssm_parameters_client_ids_stack

- name: "Deploy client region SSM parameters to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_wsr_regions}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_wsr_param_template}}"
    template_parameters:
      Key:                        "{{aws.ssm.white_space_remove_from_header_regions_key}}"
      Value:                      "{{aws.ssm.white_space_remove_from_header_regions}}"
  register: ssm_parameters_client_ids_stack
