---
- name: "Deploy SSM Postfix Documents {{stack.ssm.ssm_postfix_documents}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_postfix_documents}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_postfix_document_template}}"
    template_parameters:
      Environment:                "{{account.name}}"
  register: ssm_postfix_stack

- debug:
    var: ssm_postfix_stack
    verbosity: 3

- name: "Display SSM Postfix Documents Stack Output"
  debug:
    msg: "{{ssm_postfix_stack.stack_outputs}}"
    verbosity: 2
