---
- name: "Deploy SSM Documents {{stack.ssm.ssm_documents}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_documents}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_document_template}}"
    template_parameters:
      AlarmTopicArn:              "{{sns.arn_prefix}}{{sns.alarm_sns_topic}}"
      EipRotationLambdaFunction:  "{{lambda.eip_rotation_lambda_function}}"
  register: ssm_stack

- debug:
    var: ssm_stack
    verbosity: 3

- name: "Display SSM Documents Stack Output"
  debug:
    msg: "{{ssm_stack.stack_outputs}}"
    verbosity: 2

# Create another stack dedicated to Postfix SSM commands
- name: "Deploy SSM Postfix Documents {{stack.ssm.ssm_postfix_documents}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_postfix_documents}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_postfix_document_template}}"
    template_parameters:
      Environment:                "{{account.name}}"
  register: ssm_postfix_stack

- debug:
    var: ssm_postfix_stack
    verbosity: 3

- name: "Display SSM Postfix Documents Stack Output"
  debug:
    msg: "{{ssm_postfix_stack.stack_outputs}}"
    verbosity: 2

# Create another stack dedicated to Multi IP Management SSM
- name: "Deploy SSM Multi IP Management Document {{stack.ssm.ssm_multi_ip_document}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_multi_ip_document}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_multi_ip_document_template}}"
    template_parameters:
      Environment:                "{{account.name}}"
  register: ssm_multi_ip_stack

- debug:
    var: ssm_multi_ip_stack
    verbosity: 3

- name: "Display SSM Multi IP Management Document Stack Output"
  debug:
    msg: "{{ssm_multi_ip_stack.stack_outputs}}"
    verbosity: 2
