---
- name: "Deploy client ids SSM parameters to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_wsr_client_ids}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_wsr_param_template}}"
    template_parameters:
      Key:                        "{{aws.ssm.white-space-remove-from-header-client-ids-key}}"
      Value:                      "{{aws.ssm.xgemail.white-space-remove-from-header-client-ids}}"
  register: ssm_stack

- name: "Deploy client region SSM parameters to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_wsr_regions}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_wsr_param_template}}"
    template_parameters:
      Key:                        "{{aws.ssm.white-space-remove-from-header-regions-key}}"
      Value:                      "{{aws.ssm.xgemail.white-space-remove-from-header-regions}}"
  register: ssm_stack
