---
- name: "Deploy SSM Documents {{stack.ssm.ssm_documents}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                        "{{stack.ssm.ssm_documents}}"
    state:                             present
    region:                            "{{account.region}}"
    disable_rollback:                  true
    template:                          "{{template.ssm.ssm_xgemail_document_template}}"
    template_parameters:
      AlarmTopicArn:                   "{{sns.arn_prefix}}{{sns.alarm_sns_topic}}"
      EipRotationLambdaFunction:       "{{lambda.eip_rotation_lambda_function}}"
      MultiEipRotationLambdaFunction:  "{{lambda.multi_eip_rotation_lambda_function}}"
  register: ssm_stack

- debug:
    var: ssm_stack
    verbosity: 3

- name: "Display SSM Documents Stack Output"
  debug:
    msg: "{{ssm_stack.stack_outputs}}"
    verbosity: 2

# Create another stack dedicated to Postfix SSM commands
- name: "Deploy SSM Postfix Documents {{stack.ssm.ssm_postfix_documents}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_postfix_documents}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_postfix_document_template}}"
    template_parameters:
      Environment:                "{{account.name}}"
  register: ssm_postfix_stack

- debug:
    var: ssm_postfix_stack
    verbosity: 3

- name: "Display SSM Postfix Documents Stack Output"
  debug:
    msg: "{{ssm_postfix_stack.stack_outputs}}"
    verbosity: 2

# Create another stack dedicated to Elasticsearch data node restart SSM commands
- name: "Deploy SSM Elasticsearch Documents {{stack.ssm.ssm_elasticsearch_documents}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_elasticsearch_documents}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_elasticsearch_document_template}}"
  register: ssm_elasticsearch_stack

- debug:
    var: ssm_elasticsearch_stack
    verbosity: 3

- name: "Display SSM Elasticsearch Documents Stack Output"
  debug:
    msg: "{{ssm_elasticsearch_stack.stack_outputs}}"
    verbosity: 2

# Create another stack dedicated to create an SSM document used to stop specific ECS Tasks
- name: "Deploy SSM Ecs Container Documents {{stack.ssm.ssm_ecs_task_documents}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_ecs_task_documents}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_ecs_task_document_template}}"
  register: ssm_ecs_task_stack

- debug:
    var: ssm_ecs_task_stack
    verbosity: 3

- name: "Display SSM Ecs Container Documents Stack Output"
  debug:
    msg: "{{ssm_ecs_task_stack.stack_outputs}}"
    verbosity: 2

# Create another stack dedicated to Linux Shell SSM commands
- name: "Deploy SSM Linux Shell Documents {{stack.ssm.ssm_shell_documents}}"
  cloudformation:
    stack_name:                   "{{stack.ssm.ssm_shell_documents}}"
    state:                        present
    region:                       "{{account.region}}"
    disable_rollback:             true
    template:                     "{{template.ssm.ssm_xgemail_shell_document_template}}"
  register: ssm_shell_stack

- debug:
    var: ssm_shell_stack
    verbosity: 3

- name: "Display SSM Linux Shell Documents Stack Output"
  debug:
    msg: "{{ssm_shell_stack.stack_outputs}}"
    verbosity: 2