---
- name: "Deploy SSM Documents {{stack.ssm.ssm_documents}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:              "{{stack.ssm.ssm_documents}}"
    state:                   present
    region:                  "{{account.region}}"
    disable_rollback:        true
    template:                "{{template.ssm.ssm_xgemail_document_template}}"
    template_parameters:
      AlarmTopicArn:         "{{sns.arn_prefix}}{{sns.lifecycle_sqs_sns}}"
  register: ssm_stack

- debug:
    var: ssm_stack
    verbosity: 3

- name: "Display SSM Docuuments Stack Output"
  debug:
    msg: "{{ssm_stack.stack_outputs}}"
    verbosity: 2