name              'sophos-cloud-ntpd'
maintainer        'Sophos Email'
maintainer_email  'SophosMailOps@sophos.com'
license           'All Rights Reserved'
description       'Installs/Configures NTP'
long_description  'Installs/Configures NTP'
version           '1.0.0'
