---
- name: "Import Account Variables."
  include_vars:
    extensions: ['yml']
    dir: "{{ account.name }}"
    depth: 1

- name: "Include IAM Monitor Roles"
  include_tasks: iam-monitor-roles.yml

- name: "Include Inbound and Outbound monitor Send Receive lambda function."
  include_tasks: round-trip-monitor-deploy.yml

- name: "Include Route53 Creation Task."
  include_tasks: route53-deploy.yml

- name: "Include SES Cloud Formation Task."
  include_tasks: ses-sendreceive.yml
  when: ses.ses_deploy == 'new'

- name: "Include Custom SES Task."
  include_tasks: ses-custom-deploy.yml
  when: ses.ses_deploy == 'old'
