---
- name: "Import Account Variables."
  include_vars:
    extensions: ['yml']
    dir: "{{ account.name }}"
    depth: 1
  tags:
    - always

- name: "Include IAM Monitor Roles"
  include_tasks: iam-monitor-roles.yml

- name: "Include Inbound lambda function."
  include_tasks: round-trip-monitor-deploy.yml

- name: "Include Route53 Creation Task."
  include_tasks: route53-deploy.yml

- name: "Include SES Task."
  include_tasks: ses-sendreceive.yml