---
- name: "Deploy {{stack.route53.email_monitor_com_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_monitor_com_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{us_west_2_hostedZoneName}}."
      ResourceRecords:               "{{us_west_2_resourceRecords}}"
  register: sophos_email_monitor_us_west_2_stack_output

- debug:
     var: sophos_email_monitor_us_west_2_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_monitor_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.email_monitor_net_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_monitor_net_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{eu_central_1_hostedZoneName}}."
      ResourceRecords:               "{{eu_central_1_resourceRecords}}"
  register: sophos_email_monitor_eu_central_1_stack_output

- debug:
     var: sophos_email_monitor_eu_central_1_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_monitor_eu_central_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.email_monitor_org_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_monitor_org_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{eu_west_1_hostedZoneName}}."
      ResourceRecords:               "{{eu_west_1_resourceRecords}}"
  register: sophos_email_monitor_eu_west_1_stack_output

- debug:
     var: sophos_email_monitor_eu_west_1_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_monitor_eu_west_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.email_monitor_us_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_monitor_us_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{us_east_2_hostedZoneName}}."
      ResourceRecords:               "{{us_east_2_resourceRecords}}"
  register: sophos_email_monitor_us_east_2_stack_output

- debug:
     var: sophos_email_monitor_us_east_2_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_monitor_us_east_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.email_recipient_com_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.email_recipient_com_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{us_west_2_recipient_hostedZoneName}}."
      ResourceRecords:               "{{us_west_2_recipient_resourceRecords}}"
  register: sophos_email_recipient_us_west_2_stack_output

- debug:
     var: sophos_email_recipient_us_west_2_stack_output
     verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_recipient_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.inbound_ms_monitor_euw1_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.inbound_ms_monitor_euw1_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{ms.eu_west_1_hostedZoneName}}."
      ResourceRecords:               "{{ms.eu_west_1_resourceRecords}}"
  register: sophos_email_ms_monitor_eu_west_1_stack_output

- debug:
    var: sophos_email_ms_monitor_eu_west_1_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_ms_monitor_eu_west_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.inbound_ms_monitor_euc1_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.inbound_ms_monitor_euc1_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{ms.eu_central_1_hostedZoneName}}."
      ResourceRecords:               "{{ms.eu_central_1_resourceRecords}}"
  register: sophos_email_ms_monitor_eu_central_1_stack_output

- debug:
    var: sophos_email_ms_monitor_eu_central_1_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_ms_monitor_eu_central_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.inbound_ms_monitor_use2_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.inbound_ms_monitor_use2_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{ms.us_east_2_hostedZoneName}}."
      ResourceRecords:               "{{ms.us_east_2_resourceRecords}}"
  register: sophos_email_ms_monitor_us_east_2_stack_output

- debug:
    var: sophos_email_ms_monitor_us_east_2_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_ms_monitor_us_east_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.inbound_ms_monitor_usw2_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.inbound_ms_monitor_usw2_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{ms.us_west_2_hostedZoneName}}."
      ResourceRecords:               "{{ms.us_west_2_resourceRecords}}"
  register: sophos_email_ms_monitor_us_west_2_stack_output

- debug:
    var: sophos_email_ms_monitor_us_west_2_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_ms_monitor_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.encryption_monitor_euw1_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.encryption_monitor_euw1_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{enc.eu_west_1_hostedZoneName}}."
      ResourceRecords:               "{{enc.eu_west_1_resourceRecords}}"
  register: sophos_email_encryption_monitor_eu_west_1_stack_output

- debug:
    var: sophos_email_encryption_monitor_eu_west_1_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_encryption_monitor_eu_west_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.encryption_monitor_euc1_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.encryption_monitor_euc1_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{enc.eu_central_1_hostedZoneName}}."
      ResourceRecords:               "{{enc.eu_central_1_resourceRecords}}"
  register: sophos_email_encryption_monitor_eu_central_1_stack_output

- debug:
    var: sophos_email_encryption_monitor_eu_central_1_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_encryption_monitor_eu_central_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.encryption_monitor_use2_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.encryption_monitor_use2_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{enc.us_east_2_hostedZoneName}}."
      ResourceRecords:               "{{enc.us_east_2_resourceRecords}}"
  register: sophos_email_encryption_monitor_us_east_2_stack_output

- debug:
    var: sophos_email_encryption_monitor_us_east_2_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_encryption_monitor_us_east_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.encryption_monitor_usw2_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.encryption_monitor_usw2_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{enc.us_west_2_hostedZoneName}}."
      ResourceRecords:               "{{enc.us_west_2_resourceRecords}}"
  register: sophos_email_encryption_monitor_us_west_2_stack_output

- debug:
    var: sophos_email_encryption_monitor_us_west_2_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_encryption_monitor_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.encryption_monitor_recipient_usw2_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.encryption_monitor_recipient_usw2_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{enc.us_west_2_recipient_hostedZoneName}}."
      ResourceRecords:               "{{enc.us_west_2_recipient_resourceRecords}}"
  register: sophos_email_encryption_monitor_recipient_us_west_2_stack_output

- debug:
    var: sophos_email_encryption_monitor_recipient_us_west_2_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_encryption_monitor_recipient_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2


- name: "Deploy {{stack.route53.mf_monitor_euw1_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.mf_monitor_euw1_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{mf.eu_west_1_hostedZoneName}}."
      ResourceRecords:               "{{mf.eu_west_1_resourceRecords}}"
  register: sophos_email_mf_monitor_eu_west_1_stack_output

- debug:
    var: sophos_email_mf_monitor_eu_west_1_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_mf_monitor_eu_west_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.mf_monitor_euc1_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.mf_monitor_euc1_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{mf.eu_central_1_hostedZoneName}}."
      ResourceRecords:               "{{mf.eu_central_1_resourceRecords}}"
  register: sophos_email_mf_monitor_eu_central_1_stack_output

- debug:
    var: sophos_email_mf_monitor_eu_central_1_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_mf_monitor_eu_central_1_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.mf_monitor_use2_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.mf_monitor_use2_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{mf.us_east_2_hostedZoneName}}."
      ResourceRecords:               "{{mf.us_east_2_resourceRecords}}"
  register: sophos_email_mf_monitor_us_east_2_stack_output

- debug:
    var: sophos_email_mf_monitor_us_east_2_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_mf_monitor_us_east_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.mf_monitor_usw2_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.mf_monitor_usw2_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{mf.us_west_2_hostedZoneName}}."
      ResourceRecords:               "{{mf.us_west_2_resourceRecords}}"
  register: sophos_email_mf_monitor_us_west_2_stack_output

- debug:
    var: sophos_email_mf_monitor_us_west_2_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_mf_monitor_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2

- name: "Deploy {{stack.route53.mf_monitor_recipient_usw2_route53}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name: "{{stack.route53.mf_monitor_recipient_usw2_route53}}"
    state: present
    region: "{{account.region}}"
    disable_rollback: true
    template: "{{template.route53.route53_record_basic_template}}"
    template_parameters:
      RecordType:                    "MX"
      HostedZoneName:                "{{mf.us_west_2_recipient_hostedZoneName}}."
      ResourceRecords:               "{{mf.us_west_2_recipient_resourceRecords}}"
  register: sophos_email_mf_monitor_recipient_us_west_2_stack_output

- debug:
    var: sophos_email_mf_monitor_recipient_us_west_2_stack_output
    verbosity: 3

- name: "Display Route53 Stack Output"
  debug:
    msg: "{{sophos_email_mf_monitor_recipient_us_west_2_stack_output.stack_outputs}}"
    verbosity: 2
