@Library('msg/msg-jenkins')
@Library('devops/sophos-jenkins-shared-library')
_

pipeline {
    agent any
    options {
        buildDiscarder(
            logRotator(
                daysToKeepStr: '60',
                artifactDaysToKeepStr: '60'
            )
        )
        disableConcurrentBuilds()
        timeout(
            time: 2,
            unit: 'HOURS'
        )
    }

    parameters {
        choice(
            name: 'DEPLOYMENT_ENVIRONMENT',
            choices: [
                'inf',
                'dev',
                'perf',
                'qa',
                'prod'
            ],
            description: 'deployment environment'
        )
    }

    stages {
        stage('Generate Secrets') {
            environment {
                UNUSED = credentials("aws-cre-deployer-${params.DEPLOYMENT_ENVIRONMENT}-creds")
            }
            steps {
                dir('ansible') {

                    sh """
                    bin/create-ansible-config.sh pop

                    mkdir -p iapi-config
                    mkdir -p mongo-config
                    mkdir -p redis-config
                    mkdir -p snmp-config

                    roles/all-configs/files/create-iapi-secrets.py --output-dir iapi-config
                    roles/all-configs/files/create-mongo-config.py --output-dir mongo-config
                    roles/all-configs/files/create-redis-core-token.py --output-dir redis-config
                    roles/all-configs/files/create-snmp-creds.py --output-dir snmp-config

                    ansible-vault encrypt iapi-config/iapi_vaulted.yml
                    ansible-vault encrypt mongo-config/mongo-users_vaulted.yml
                    ansible-vault encrypt mongo-config/mongo-vars_vaulted.yml
                    ansible-vault encrypt redis-config/redis-core-cluster-vars_vaulted.yml
                    ansible-vault encrypt snmp-config/snmp-credentials_vaulted.yml

                    cat iapi-config/iapi_vaulted.yml
                    cat mongo-config/mongo-users_vaulted.yml
                    cat mongo-config/mongo-vars_vaulted.yml
                    cat mongo-config/mongo-vars.yml
                    cat redis-config/redis-core-cluster-vars_vaulted.yml
                    cat snmp-config/snmp-credentials_vaulted.yml
                    cat snmp-config/snmp-credentials.yml
                    """

                    archiveArtifacts(
                        artifacts: 'iapi-config/*,mongo-config/*,redis-config/*,snmp-config/*',
                        fingerprint: true,
                        followSymlinks: false,
                        onlyIfSuccessful: true
                    )
                }
            }
        }
    }
}
