---
#- name: Debug
#  debug:
#    msg: "{{item.value.stack_name}} {{item.value.AutoScalingMinSize}} {{item.value.AvailabilityZoneIndex}} {{item.value.VolumeSetId}} {{cloud_email_iam_output.stack_outputs.AutoScalingInstanceRoleArn}}"
#  with_dict: "{{aws.ec2.asg.cd}}"

- name: "Create ASG Stacks in AWS"
  async: 100
  poll: 0
  cloudformation:
    stack_name: "{{vpc.cloud_email.name}}-xgemail-internet-xdelivery-0000-{{item.0}}"
    state: present
    region:  "{{account.region}}"
    disable_rollback: true
    template: "{{template.ec2.asg.as_xgemail_xdelivery_template}}"
    template_parameters:
      AesDecryptionKey:                     "{{aes_decryption_key}}"
      AmiId:                                "{{ami_parent_id}}"
      AutoScalingMinSize:                   "1"
      AutoScalingMaxSize:                   "1"
      AutoScalingNotificationTopicARN:      "{{sns.arn_prefix}}{{sns.lifecycle_sqs_sns}}"
      AvailabilityZoneIndex:                "{{item.1}}"
      AvailabilityZones:                    "{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.AvailabilityZoneA}},{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.AvailabilityZoneB}},{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.AvailabilityZoneC}}"
      Branch:                               "{{build.branch}}"
      BuildVersion:                         "{{build.result_key}}"
      BundleVersion:                        "{{ami_build}}"
      EbsMinIops:                           "{{xgemail_iops_data_gb}}"
      Environment:                          "{{account.name}}"
      HealthCheckGracePeriod:               "{{health_check_grace_period_ix}}"
      HealthCheckType:                      "ELB"
      InstanceProfile:                      "{{cloud_email_iam_output.ansible_facts.cloudformation[stack.iam.cloud_email_roles].stack_outputs.XgemailInternetXdeliveryInstanceProfile}}"
      InstanceType:                         "{{instance_size_ix}}"
      KeyName:                              "public-{{account.region}}"
      LoadBalancerName:                     "{{elb_stack_output.stack_outputs.LoadBalancerId}}"
      PublicIpAddressEnabled:               "true"
      S3CookbookRepositoryURL:              "//cloud-{{account.name}}-templates/{{build.branch}}/xgemail-infrastructure/cookbooks.enc"
      ScaleDownOnWeekends:                  "{{weekend_scale_down}}"
      SecurityGroups:                       "{{cloud_email_sg_output.ansible_facts.cloudformation[stack.ec2.sg.cloud_email_security_groups].stack_outputs.XgemailInternetXdeliverySecurityGroup}},{{cloud_email_sg_output.ansible_facts.cloudformation[stack.ec2.sg.cloud_email_security_groups].stack_outputs.SecurityGroupBase}}"
      SpotPrice:                            "{{instance_size_xgemail_spot_price}}"
      StationVpcName:                       "{{vpc.cloud_station.name}}"
      VolumeSetId:                          "internet-xdelivery-{{item.0}}"
      VolumeTrackerSimpleDbDomain:          "{{volume_tracker_sdb_output.ansible_facts.cloudformation[stack.sdb.volume_tracker_sdb].stack_outputs.SimpleDbDomain}}"
      Vpc:                                  "{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.Vpc}}"
      VpcZoneIdentifiers:                   "{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.PublicSubnetA}},{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.PublicSubnetB}},{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.PublicSubnetC}}"
      VpcName:                              "{{vpc.cloud_email.name}}"
      XgemailMinSizeDataGB:                 "{{xgemail_size_data_gb}}"
      XgemailMsgHistoryStatusSNSArn:        "{{sns.arn_prefix}}{{sqs.msg_history_status_sns_topic}}"
      XgemailServiceType:                   "internet-xdelivery"
  with_together:
    - "{{stack_number}}"
    - "{{zone_index}}"
  register: ix_stack_async_results

- async_status:
    jid: "{{item.ansible_job_id}}"
  with_items: "{{ix_stack_async_results.results}}"
  register: ix_stack_async_poll_results
  until: "{{ix_stack_async_poll_results.finished}}"
  retries: 50