---
# Inbound Monitor receive lambda function output
- name: "Gather {{stack.lambda.inbound_monitor_receive_lambda_function}} CloudFormation Stack Output"
  cloudformation_facts:
    stack_name: "{{stack.lambda.inbound_monitor_receive_lambda_function}}"
    region: "{{account.region}}"
  register: inbound_monitor_receive_lambda_output

- name: "Print {{stack.lambda.inbound_monitor_receive_lambda_function}} CloudFormation Stack Output"
  debug:
    var: inbound_monitor_receive_lambda_output
    verbosity: 3

# Outbound Monitor receive lambda function output
- name: "Gather {{stack.lambda.outbound_monitor_receive_lambda_function}} CloudFormation Stack Output"
  cloudformation_facts:
    stack_name: "{{stack.lambda.outbound_monitor_receive_lambda_function}}"
    region: "{{account.region}}"
  register: outbound_monitor_receive_lambda_output

- name: "Print {{stack.lambda.outbound_monitor_receive_lambda_function}} CloudFormation Stack Output"
  debug:
    var: outbound_monitor_receive_lambda_output
    verbosity: 3