---
- name: "Deploy SES  {{stack.ses.email_monitor_ses}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:                             "{{stack.ses.email_monitor_ses}}"
    state:                                  present
    region:                                 "{{account.region}}"
    disable_rollback:                       true
    template:                               "{{template.ses.ses_template}}"
    template_parameters:
      InboundRuleName:                      "xgemail-monitor-rule"
      OutboundRuleName:                     "xgemail-outbound-monitor-rule"
      RuleSetName:                          "{{ses_rule_set_name}}"
      SesInvokeLambdaFunctionArn:           "{{inbound_monitor_receive_lambda_output.ansible_facts.cloudformation[stack.lambda.inbound_monitor_receive_lambda_function].stack_outputs.LambdaFunctionArn}}"
      SesInvokeOutboundLambdaFunctionArn:   "{{outbound_monitor_receive_lambda_output.ansible_facts.cloudformation[stack.lambda.outbound_monitor_receive_lambda_function].stack_outputs.LambdaFunctionArn}}"
      InboundMailRecipients:                "{{inbound_mail_recipients}}"
      OutboundMailRecipients:               "{{outbound_mail_recipients}}"
      Domains:                              "{{domains}}"
  register: ses_stack_output

- debug:
    var: ses_stack_output
    verbosity: 3

- name: "Display SES Stack Output"
  debug:
    msg: "{{ses_stack_output.stack_outputs}}"
    verbosity: 2