---
# Ansible version required: 2.4.0
# -----------------------------------
# Execute: ansible-playbook -vvv ./playbooks/deploy-cloud-email-is.yml --extra-vars="aws_region=${REGION} aws_account=${ENVIRONMENT} branch_name=${bamboo_planRepository_branchName} branch_build=${bamboo_buildNumber} vpc_name=${VPC_NAME}"
# -----------------------------------
- hosts: localhost
  gather_facts: no
  connection: local

  roles:
    - { role: internet-submit, stack_number: [1,2,3,4,5,6], asg_min_size: [0,0,0,1,1,1], zone_index: [0,1,2,0,1,2] }
