---
# Ansible version required: 2.4.0
# -----------------------------------
# Execute: ansible-playbook -vvv ./playbooks/retrieve-connector.yml --extra-vars="deploy=False aws_region=${REGION} aws_account=${ENVIRONMENT}"
# -----------------------------------
- hosts: localhost
  gather_facts: no
  connection: local

  roles:
    - retrieve-connector