aws_account_id: 283871543274
connector_env: 352a48c0-9f78-4e73-8678-f424673e072e
connector_env_newboo: 45ad1c14-edde-48a1-a36c-e3e7c986998a
cloud_applications: cloud-inf-templates
instance_size_xgemail_spot_price:               .11
mail_domain: p0.i.hmr.sophos.com
aws:
  asg:
    cd:
      stack_number:                             [1,2,3,4,5,6,7,8,9,10,11,12]
      asg_min_size:                             [0,0,0,0,0,0,0,0,0,0,0,1]
      zone_index:                               [0,1,2,0,1,2,0,1,2,0,1,2]
    cs:
      stack_number:                             [1,2,3,4,5,6]
      asg_min_size:                             [0,0,0,0,0,1]
      zone_index:                               [0,1,2,0,1,2]
    cx:
      stack_number:                             [1,2,3]
      zone_index:                               [0,1,2]
    id:
      stack_number:                             [1,2,3,4,5,6,7,8,9,10,11,12]
      asg_min_size:                             [0,0,0,0,0,0,0,0,0,0,0,1]
      zone_index:                               [0,1,2,0,1,2,0,1,2,0,1,2]
    is:
      stack_number:                             [1,2,3,4,5,6]
      asg_min_size:                             [0,0,0,0,0,1]
      zone_index:                               [0,1,2,0,1,2]
    ix:
      stack_number:                             [1,2,3]
      zone_index:                               [0,1,2]