source 'https://api.berkshelf.com'

require File.expand_path('../../../lib/berksfile_helper.rb', __FILE__)

sophos_cookbook 'sophos-cloud-common'
sophos_cookbook 'sophos-cloud-smc'
sophos_cookbook 'sophos-cloud-fluentd'
sophos_cookbook 'sophos-cloud-ami'
sophos_cookbook 'tar'
sophos_cookbook 's3_file'


metadata
