---

- name: "Create ASG Stack in AWS"
  cloudformation:
    stack_name: "{{stack.ec2.asg.mfos}}"
    state: present
    region:  "{{account.region}}"
    disable_rollback: no
    template: "{{template.ec2.asg.as_mf_outbound_submit_template}}"
    template_parameters:
      AesDecryptionKey:                     "{{aes_decryption_key}}"
      AlarmTopicArn:                        "{{sns.arn_prefix}}{{sns.alarm_sns_topic}}"
      AmiId:                                "{{ami_parent_id}}"
      AutoScalingInstanceRoleArn:           "{{cloud_email_iam_output.ansible_facts.cloudformation[stack.iam.role.cloud_email_roles].stack_outputs.AutoScalingInstanceRoleArn}}"
      AutoScalingMinSize:                   "{{aws.asg.mfos.as_min_size}}"
      AutoScalingMaxSize:                   "{{aws.asg.mfos.as_max_size}}"
      AutoScalingNotificationTopicARN:      "{{sns.arn_prefix}}{{sns.lifecycle_sqs_sns}}"
      AvailabilityZones:                    "{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.AvailabilityZones}}"
      Branch:                               "{{build.branch}}"
      BuildVersion:                         "{{build.result_key}}"
      BundleVersion:                        "{{ami_build}}"
      DeliveryDirectorBucketName:           "{{s3.delivery_director_bucket}}"
      DeployMaxBatchSize:                   "{{aws.asg.mfos.as_max_batch_size}}"
      DeployMinInstancesInService:          "{{aws.asg.mfos.as_min_service}}"
      Environment:                          "{{account.name}}"
      HealthCheckGracePeriod:               "{{aws.asg.mfos.health_check_grace_period}}"
      InstanceProfile:                      "{{cloud_email_iam_output.ansible_facts.cloudformation[stack.iam.role.cloud_email_roles].stack_outputs.XgemailMfOutboundSubmitInstanceProfile}}"
      InstanceType:                         "{{aws.asg.mfos.instance_size}}"
      KeyName:                              "public-{{account.region}}"
      LifecycleHookTerminating:             "{{aws.asg.mfos.lifecycle_hook_terminating}}"
      LoadBalancerName:                     "{{elb_stack_output.stack_outputs.LoadBalancerId}}"
      MsgHistoryV2BucketName:               "{{s3.msg_history_v2_bucket_name}}"
      MsgHistoryV2StreamName:               "{{kinesis.firehose.msg_history_v2_stream_name}}"
      MessageHistoryEventsTopicArn:         "{{sns.arn_prefix}}{{sns.msg_history_events_sns_topic}}"
      NewRelicEnabled:                      "{{newrelic_enabled}}"
      PolicyTargetValue:                    "{{aws.asg.mfos.policy_target_value}}"
      S3CookbookRepositoryURL:              "//cloud-{{account.name}}-templates/{{build.branch}}/xgemail-infrastructure/cookbooks.enc"
      SecurityGroups:                       "{{cloud_email_sg_output.ansible_facts.cloudformation[stack.ec2.sg.cloud_email_security_groups].stack_outputs.XgemailMfOutboundSubmitSecurityGroup}},{{cloud_email_sg_output.ansible_facts.cloudformation[stack.ec2.sg.cloud_email_security_groups].stack_outputs.SecurityGroupBase}}"
      SpotPrice:                            "{{spot_price}}"
      StationVpcId:                         "{{cloud_station_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_station_vpc].stack_outputs.Vpc}}"
      StationVpcName:                       "{{vpc.cloud_station.name}}"
      Vpc:                                  "{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.Vpc}}"
      VpcZoneIdentifiers:                   "{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.PublicSubnetA}},{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.PublicSubnetB}},{{cloud_email_vpc_output.ansible_facts.cloudformation[stack.vpc.cloud_email_vpc].stack_outputs.PublicSubnetC}}"
      VpcName:                              "{{vpc.cloud_email.name}}"
      XgemailBucketName:                    "{{s3.customer_submit_bucket}}"
      XgemailMinSizeDataGB:                 "{{xgemail_size_data_gb}}"
      XgemailMsgHistoryBucketName:          "{{s3.msg_history_bucket}}"
      XgemailMsgHistoryMsBucketName:        "{{s3.msg_history_ms_bucket}}"
      XgemailMsgHistoryQueueUrl:            "{{sqs.url_prefix}}{{sqs.msg_history_sqs_queue}}"
      XgemailPolicyArn:                     "{{sns.arn_prefix}}{{sns.relay_control_sns_topic}}"
      XgemailPolicyBucketName:              "{{s3.policy_bucket}}"
      XgemailPolicyEfsFileSystemId:         "{{cloud_email_efs_output.ansible_facts.cloudformation[stack.efs.policy_efs_volume].stack_outputs.FileSystemId}}"
      XgemailPostfixQueueEfsFileSystemId:   "{{cloud_email_postfix_queue_efs_output.ansible_facts.cloudformation[stack.efs.postfix_queue_efs_volume].stack_outputs.FileSystemId}}"
      XgemailQueueUrl:                      "{{sqs.url_prefix}}{{sqs.customer_submit_sqs_queue}}"
      XgemailScanEventsTopicArn:            "{{sns.arn_prefix}}{{sns.scan_events_sns_topic}}"
      XgemailServiceType:                   "mf-outbound-submit"
      XgemailSxlDbl:                        "{{xgemail_sxl_dbl}}"
      XgemailSxlRbl:                        "{{xgemail_sxl_rbl}}"
  register: asg_stack_output

- debug:
    var: asg_stack_output
    verbosity: 3

- name: "Display ASG Stack Output"
  debug:
    msg: "{{asg_stack_output.stack_outputs}}"
    verbosity: 2