---
aws_account_id:                             "283871543274"
eu_central_1_hostedZoneName:                "sophos-email-inf-eu-central-1-monitor.com"
eu_central_1_resourceRecords:               "10 mx-01-eu-central-1.inf.hydra.sophos.com.,20 mx-02-eu-central-1.inf.hydra.sophos.com."
eu_west_1_hostedZoneName:                   "sophos-email-inf-eu-west-1-monitor.com"
eu_west_1_resourceRecords:                  "10 mx-01-eu-west-1.inf.hydra.sophos.com.,20 mx-02-eu-west-1.inf.hydra.sophos.com."
us_east_2_hostedZoneName:                   "sophos-email-inf-us-east-2-monitor.com"
us_east_2_resourceRecords:                  "10 mx-01-us-east-2.inf.hydra.sophos.com.,20 mx-02-us-east-2.inf.hydra.sophos.com."
us_west_2_hostedZoneName:                   "sophos-email-inf-us-west-2-monitor.com"
us_west_2_resourceRecords:                  "10 mx-01-us-west-2.inf.hydra.sophos.com.,20 mx-02-us-west-2.inf.hydra.sophos.com."
us_west_2_recipient_hostedZoneName:         "sophos-email-inf-us-west-2-recipient.com"
us_west_2_recipient_resourceRecords:        "10 inbound-smtp.inf.us-west-2.amazonaws.com."
eu_central_1_mailbox_name:                  "eu.central.1.inf@sophos-email-inf-eu-central-1-monitor.com"
eu_west_1_mailbox_name:                     "eu.west.1.inf@sophos-email-inf-eu-west-1-monitor.com"
us_east_2_mailbox_name:                     "us.east.2.inf@sophos-email-inf-us-east-2-monitor.com"
us_west_2_mailbox_name:                     "us.west.2.inf@sophos-email-inf-us-west-2-monitor.com"
us_west_2_sender_mailbox_name:              "monitor.sender@sophos-email-inf-us-west-2-monitor.com"
eu_central_1_id:                            "6c5cba1d-35fe-4de1-b5f5-97f5e013df99"
eu_central_1_private_key:                   "sophos-email-inf-eu-central-1-monitor.com.key"
eu_central_1_public_key:                    "sophos-email-inf-eu-central-1-monitor.com.crt"
eu_central_1_public_thumb_print:            "sophos-email-inf-eu-central-1-monitor.com_sha1.txt"
eu_west_1_id:                               "16404cae-a875-45be-94eb-4d55bb974e9e"
eu_west_1_private_key:                      "sophos-email-inf-eu-west-1-monitor.com.key"
eu_west_1_public_key:                       "sophos-email-inf-eu-west-1-monitor.com.crt"
eu_west_1_public_thumb_print:               "sophos-email-inf-eu-west-1-monitor.com_sha1.txt"
tenant_id:                                  "baf0da6e-b644-43a5-98a8-e14ed39b8d02"
us_east_2_id:                               "3611d007-d145-4721-97bb-fb129bd2788c"
us_east_2_private_key:                      "sophos-email-inf-us-east-2-monitor.com.key"
us_east_2_public_key:                       "sophos-email-inf-us-east-2-monitor.com.crt"
us_east_2_public_thumb_print:               "sophos-email-inf-us-east-2-monitor.com_sha1.txt"
us_west_2_id:                               "d6c9b096-233d-409d-bb8e-07b4d5b1defb"
us_west_2_private_key:                      "sophos-email-inf-us-west-2-monitor.com.key"
us_west_2_public_key:                       "sophos-email-inf-us-west-2-monitor.com.crt"
us_west_2_public_thumb_print:               "sophos-email-inf-us-west-2-monitor.com_sha1.txt"
ses_rule_set_name:                          "us-west-2-rule-set"
ses_region:                                 "eu-west-1"
eu_central_1a_cidr:                         "52.29.100.147/32"
eu_central_1b_cidr:                         "52.58.166.242/32"
eu_west_1a_cidr:                            "52.31.106.198/32"
eu_west_1b_cidr:                            "52.208.126.243/32"
us_east_2a_cidr:                            "18.220.12.142/32"
us_east_2b_cidr:                            "18.216.7.10/32"
us_west_2a_cidr:                            "50.112.39.248/32"
us_west_2b_cidr:                            "52.41.236.76/32"
inbound_mail_recipients:                    "us.west.2.inf@sophos-email-inf-us-west-2-monitor.com, eu.central.1.inf@sophos-email-inf-eu-central-1-monitor.com, eu.west.1.inf@sophos-email-inf-eu-west-1-monitor.com, us.east.2.inf@sophos-email-inf-us-east-2-monitor.com"
outbound_mail_recipients:                   "sophos-email-inf-us-west-2-recipient.com, monitor.recipient@sophos-email-inf-us-west-2-recipient.com"
domains:                                    "sophos-email-inf-eu-central-1-monitor.com, sophos-email-inf-us-west-2-monitor.com, sophos-email-inf-eu-west-1-monitor.com, sophos-email-inf-us-east-2-monitor.com, sophos-email-inf-us-west-2-recipient.com"

ms:
  eu_west_1_mailbox_name:                       "eu.west.1.inf@sophos-email-ms-inf-eu-west-1-monitor.com"
  eu_central_1_mailbox_name:                    "eu.central.1.inf@sophos-email-ms-inf-eu-central-1-monitor.com"
  us_east_2_mailbox_name:                       "us.e2.inf@sophos-email-ms-inf-us-east-2-monitor.com"
  us_west_2_mailbox_name:                       "us.west.2.inf@sophos-email-ms-inf-us-west-2-monitor.com"
  us_west_2_sender_mailbox_name:                "monitor.sender@sophos-email-ms-inf-us-west-2-monitor.com"
  eu_west_1_hostedZoneName:                     "sophos-email-ms-inf-eu-west-1-monitor.com"
  eu_west_1_resourceRecords:                    "10 mx-01-eu-west-1.inf.hydra.sophos.com.,20 mx-02-eu-west-1.inf.hydra.sophos.com."
  eu_central_1_hostedZoneName:                  "sophos-email-ms-inf-eu-central-1-monitor.com"
  eu_central_1_resourceRecords:                 "10 mx-01-eu-central-1.inf.hydra.sophos.com.,20 mx-02-eu-central-1.inf.hydra.sophos.com."
  us_east_2_hostedZoneName:                     "sophos-email-ms-inf-us-east-2-monitor.com"
  us_east_2_resourceRecords:                    "10 mx-01-us-east-2.inf.hydra.sophos.com.,20 mx-02-us-east-2.inf.hydra.sophos.com."
  us_west_2_hostedZoneName:                     "sophos-email-ms-inf-us-west-2-monitor.com"
  us_west_2_resourceRecords:                    "10 mx-01-us-west-2.inf.hydra.sophos.com.,20 mx-02-us-west-2.inf.hydra.sophos.com."
  inbound_ms_mail_recipients:                   "eu.west.1.inf@sophos-email-ms-inf-eu-west-1-monitor.com, eu.central.1.inf@sophos-email-ms-inf-eu-central-1-monitor.com, us.e2.inf@sophos-email-ms-inf-us-east-2-monitor.com, us.west.2.inf@sophos-email-ms-inf-us-west-2-monitor.com"

mf:
  eu_central_1_hostedZoneName:                  "xgemail-mf-inf-eu-c1-monitor.com"
  eu_central_1_resourceRecords:                 "10 mx-01-eu-central-1.inf.hydra.sophos.com.,20 mx-02-eu-central-1.inf.hydra.sophos.com."
  eu_west_1_hostedZoneName:                     "xgemail-mf-inf-eu-w1-monitor.com"
  eu_west_1_resourceRecords:                    "10 mx-01-eu-west-1.inf.hydra.sophos.com.,20 mx-02-eu-west-1.inf.hydra.sophos.com."
  us_east_2_hostedZoneName:                     "xgemail-mf-inf-us-e2-monitor.com"
  us_east_2_resourceRecords:                    "10 mx-01-us-east-2.inf.hydra.sophos.com.,20 mx-02-us-east-2.inf.hydra.sophos.com."
  us_west_2_hostedZoneName:                     "xgemail-mf-inf-us-w2-monitor.com"
  us_west_2_resourceRecords:                    "10 mx-01-us-west-2.inf.hydra.sophos.com.,20 mx-02-us-west-2.inf.hydra.sophos.com."
  us_west_2_recipient_hostedZoneName:           "xgemail-mf-inf-us-w2-monitor.com"
  us_west_2_recipient_resourceRecords:          "10 inbound-smtp.us-west-2.amazonaws.com."
  eu_central_1_mailbox_name:                    "mailflow-euc1@xgemail-mf-inf-eu-c1-monitor.com"
  eu_west_1_mailbox_name:                       "mailflow-euw1@xgemail-mf-inf-eu-w1-monitor.com"
  us_east_2_mailbox_name:                       "mailflow-use2@xgemail-mf-inf-us-e2-monitor.com"
  us_west_2_mailbox_name:                       "mailflow-usw2@xgemail-mf-inf-us-w2-monitor.com"
  eu_central_1_id:                              "b0eacc47-d913-41c5-9829-0351f7e4053e"
  eu_central_1_private_key:                     "xgemail-mf-inf-eu-c1-monitor.com.key"
  eu_central_1_public_key:                      "xgemail-mf-inf-eu-c1-monitor.com.crt"
  eu_central_1_public_thumb_print:              "xgemail-mf-inf-eu-c1-monitor.com_sha1.txt"
  eu_west_1_id:                                 "d9952071-2848-4970-8a8e-a58391327d92"
  eu_west_1_private_key:                        "xgemail-mf-inf-eu-w1-monitor.com.key"
  eu_west_1_public_key:                         "xgemail-mf-inf-eu-w1-monitor.com.crt"
  eu_west_1_public_thumb_print:                 "xgemail-mf-inf-eu-w1-monitor.com_sha1.txt"
  us_east_2_id:                                 "c2f8bc46-6560-4237-8cbb-29a47aac7929"
  us_east_2_private_key:                        "xgemail-mf-inf-us-e2-monitor.com.key"
  us_east_2_public_key:                         "xgemail-mf-inf-us-e2-monitor.com.crt"
  us_east_2_public_thumb_print:                 "xgemail-mf-inf-us-e2-monitor.com_sha1.txt"
  us_west_2_id:                                 "e5306486-4f63-4e85-bee7-2d0fff444cc1"
  us_west_2_private_key:                        "xgemail-mf-inf-us-w2-monitor.com.key"
  us_west_2_public_key:                         "xgemail-mf-inf-us-w2-monitor.com.crt"
  us_west_2_public_thumb_print:                 "xgemail-mf-inf-us-w2-monitor.com_sha1.txt"
  us_west_2_sender_mailbox_name:                "monitor.sender@xgemail-mf-inf-us-w2-monitor.com"
  mf_outbound_mail_recipients:                  "xgemail-mf-inf-us-w2-monitor.com, monitor.recipient@xgemail-mf-inf-us-w2-monitor.com"
  mf_inbound_mail_recipients:                   "mailflow-euc1@xgemail-mf-inf-eu-c1-monitor.com, mailflow-euw1@xgemail-mf-inf-eu-w1-monitor.com, mailflow-use2@xgemail-mf-inf-us-e2-monitor.com, mailflow-usw2@xgemail-mf-inf-us-w2-monitor.com"
