#!/bin/bash
# vim: autoindent expandtab shiftwidth=4 filetype=sh

# Copyright 2018, Sophos Limited. All rights reserved.
#
# 'Sophos' and 'Sophos Anti-Virus' are registered trademarks of
# Sophos Limited and Sophos Group.  All other product and company
# names mentioned are trademarks or registered trademarks of their
# respective owners.

# TODO ;;; Support collection of Java call stacks too.
# See https://medium.com/netflix-techblog/java-in-flames-e763b3d32166
# and https://blog.codecentric.de/en/2017/09/jvm-fire-using-flame-graphs-analyse-performance/.
# This will require telling the JVM to preserve frame points, and using
# an agent to export method mappings generated by the JIT compiler.

set -o errexit
set -o nounset
set -o pipefail

if [ "${1-}" = "-h" ] || [[ "${1-}" = *"help"* ]]; then
    cat <<EOF
Usage: $0 [<SLEEP-DURATION>]

Runs 'perf record -a -g -F99' to collect system call graph samples for
all CPUs 99 times per second, then generates an HTML rendering of the
results as a flamegraph and uploads the HTML to S3.

Examples:
    $0      # collect for default 1 minute
    $0 30   # collect for 30 seconds
    $0 5m   # newer versions of sleep let you specify time units
EOF
    exit 0
fi

if [ "$#" -gt 1 ]; then
    echo "$0: -- too many arguments" 1>&2
    exit 2
fi

WORKING_DIRECTORY="/tmp/$(basename "$0").d"
mkdir -p "${WORKING_DIRECTORY}"
cd "${WORKING_DIRECTORY}"
trap 'cd /tmp; rm -rf ${WORKING_DIRECTORY}' EXIT

SLEEPTIME="${1-60}"

MONGODB_INSTANCE_ATTRIBUTE_FILE="/var/sophos/cookbooks/instance-attributes.json"

MONGOS_BASE_FILE="/var/chef/roles/base.json"

if [ ! -e "${MONGODB_INSTANCE_ATTRIBUTE_FILE}" ]; then
    ACCOUNT="$(jq -r .default_attributes.sophos_cloud.environment ${MONGOS_BASE_FILE})"
    REGION="$(jq -r .default_attributes.sophos_cloud.region ${MONGOS_BASE_FILE})"
    VPCNAME="$(jq -r .default_attributes.sophos_cloud.vpc_name ${MONGOS_BASE_FILE})"

else
    ACCOUNT="$(jq -r .sophos_cloud.environment ${MONGODB_INSTANCE_ATTRIBUTE_FILE})"
    REGION="$(jq -r .sophos_cloud.region ${MONGODB_INSTANCE_ATTRIBUTE_FILE})"
    VPCNAME="$(jq -r .sophos_cloud.vpc_name ${MONGODB_INSTANCE_ATTRIBUTE_FILE})"

fi

VPCLOWER="$(echo "${VPCNAME}" | tr '[:upper:]' '[:lower:]')"

if [ -r /opt/sophos/service ]; then
    SERVICE="$(head -1 /opt/sophos/service)"
else
    SERVICE="$(jq -r .sophos_cloud.application_name /var/sophos/cookbooks/instance-attributes.json)"
fi

INST="$(/opt/aws/bin/ec2-metadata -i | awk '{print $NF}')"

BUCKET=cloud-${ACCOUNT}-logs

KEY="$(date "+%Y/%m/%d-%a/reports/flamegraphs/${REGION}/${VPCNAME}/%Y%m%d.%H%M%S-${ACCOUNT}-${REGION}-${VPCLOWER}-${SERVICE}-${INST}.html")"

PERFDATA="${WORKING_DIRECTORY}/perf.data.$$"

PERFCOMMAND="perf record -a -g -F 99 -o ${PERFDATA} -- sleep ${SLEEPTIME}"

echo "Running: ${PERFCOMMAND}"
${PERFCOMMAND}

perf script -i "${PERFDATA}" | sed -e 's/^conn[0-9][0-9]* /connNUM /' | /opt/flamegraph/stackcollapse-perf.pl | /opt/flamegraph/flamegraph.pl > perf.svg
(
  echo "<html><head><title>$(hostname): perf record $*</title></head><body>"
  echo "<h2>CPU call graph samples</h2>"
  echo "<p>"
  echo "<ul>"
  echo "<li>Serv: ${SERVICE}"
  echo "<li>Host: ${ACCOUNT}/${REGION}/${VPCNAME}/${INST}"
  echo "<li>Date: $(date)"
  echo "<li>Comm: ${PERFCOMMAND}"
  echo "</ul>"
  echo "<p>"
  sed -n '/<svg/,$p' perf.svg
  echo "</body></html>"
) > perf.html

aws s3 cp --region us-west-2 perf.html "s3://${BUCKET}/${KEY}"
