#!/usr/bin/env python
# vim: autoindent expandtab tabstop=4 softtabstop=4 shiftwidth=4 filetype=python

# Copyright 2016, Sophos Limited. All rights reserved.
#
# 'Sophos' and 'Sophos Anti-Virus' are registered trademarks of
# Sophos Limited and Sophos Group.  All other product and company
# names mentioned are trademarks or registered trademarks of their
# respective owners.

# check_yaml: Check syntax of each yaml file listed on the command line.

import sys
import yaml


def check_yaml(path):
    try:
        with open(path) as fp:
            yaml.load(fp)
        return True
    except Exception as e:
        print >> sys.stderr, "%s: %s" % (path, e)
        return False


def main():
    paths = sys.argv[1:]

    failed = False
    for path in paths:
        if not check_yaml(path):
            failed = True

    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
