#!/bin/bash
# vim: autoindent expandtab tabstop=4 softtabstop=4 shiftwidth=4 filetype=python

# Copyright 2016, Sophos Limited. All rights reserved.
#
# 'Sophos' and 'Sophos Anti-Virus' are registered trademarks of
# Sophos Limited and Sophos Group.  All other product and company
# names mentioned are trademarks or registered trademarks of their
# respective owners.

# check_chefspec: Execute chefspec tests against all recipes.

rc=0

set -o pipefail

for f in $*; do
    printf "%s: " $f
    if chef exec rspec $f > /dev/null; then
        echo OK
    else
        rc=1
    fi
done

exit $rc
