#!/usr/bin/env python
# vim: autoindent expandtab tabstop=4 softtabstop=4 shiftwidth=4 filetype=python

# Copyright 2016, Sophos Limited. All rights reserved.
#
# 'Sophos' and 'Sophos Anti-Virus' are registered trademarks of
# Sophos Limited and Sophos Group.  All other product and company
# names mentioned are trademarks or registered trademarks of their
# respective owners.

# check_docker: Check syntax of each docker file listed on the command line.

import os
import subprocess
import sys

def check_docker(path):
    try:
        subprocess.check_output([
            'hadolint',
            # https://github.com/hadolint/hadolint/wiki/DL3002 Do not switch to root USER
            '--ignore',
            'DL3002',
            # https://github.com/hadolint/hadolint/wiki/DL3004 Do not use sudo
            '--ignore',
            'DL3004',
            # https://github.com/hadolint/hadolint/wiki/DL3019 Use the --no-cache switch
            '--ignore',
            'DL3019',
            # https://github.com/hadolint/hadolint/wiki/DL4000 MAINTAINER is deprecated
            '--ignore',
            'DL4000',
            path
        ])
        return True
    except subprocess.CalledProcessError as cpe:
        print >> sys.stderr, "%s: %s" % (path, cpe.output)
        return False
    except OSError as ose:
        print >> sys.stderr, ("Must have hadolint installed for docker "
                              "linting. brew install hadolint on Mac.\n%s"
                              % ose)
        sys.exit(0)

def main():
    paths = sys.argv[1:]

    failed = False
    for path in paths:
        if not check_docker(path):
            failed = True

    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
