#!/usr/bin/python
# vim: autoindent expandtab tabstop=4 softtabstop=4 shiftwidth=4 filetype=python

# Copyright 2016, Sophos Limited. All rights reserved.
#
# 'Sophos' and 'Sophos Anti-Virus' are registered trademarks of
# Sophos Limited and Sophos Group.  All other product and company
# names mentioned are trademarks or registered trademarks of their
# respective owners.

# check_ruby: Check syntax of each ruby source file listed on the command line.

import subprocess
import sys


def check_ruby(path):
    rc = subprocess.call(["ruby", "-c", path], stdout=subprocess.PIPE)
    return True if rc == 0 else False


def main():
    paths = sys.argv[1:]

    failed = False
    for path in paths:
        if not check_ruby(path):
            failed = True

    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
