#!/usr/bin/env python
# vim: autoindent expandtab tabstop=4 softtabstop=4 shiftwidth=4 filetype=python

# Copyright 2018, Sophos Limited. All rights reserved.
#
# 'Sophos' and 'Sophos Anti-Virus' are registered trademarks of
# Sophos Limited and Sophos Group.  All other product and company
# names mentioned are trademarks or registered trademarks of their
# respective owners.

"""
Check ansible playbooks files for common errors.
"""

import sys
import os
from subprocess import Popen, PIPE

root_prefix = 'ansible/playbooks'


def check_ansible(playbook):
    p = Popen(["ansible-playbook", "--syntax-check", "-i", "localhost", '-vvv', playbook], stdin=PIPE, stdout=PIPE, stderr=PIPE, cwd='ansible')
    output, err = p.communicate()
    rc = p.returncode
    return True if rc == 0 else False


def main():
    paths = sys.argv[1:]

    failed = False
    for path in paths:
        print path
        if root_prefix in path:
            basename = os.path.basename(path)
            playbook = 'playbooks/' + basename
            if not check_ansible(playbook):
                failed = True

    sys.exit(1 if failed else 0)


if __name__ == '__main__':
    main()
