#!/usr/bin/env python
# vim: autoindent expandtab tabstop=4 softtabstop=4 shiftwidth=4 filetype=python

# Copyright 2018, Sophos Limited. All rights reserved.
#
# 'Sophos' and 'Sophos Anti-Virus' are registered trademarks of
# Sophos Limited and Sophos Group.  All other product and company
# names mentioned are trademarks or registered trademarks of their
# respective owners.

# check_cloudformation: Check syntax of each cloudformation file listed on the command line.

import sys
import boto3
from botocore.exceptions import BotoCoreError, ClientError

cfn = boto3.client('cloudformation', region_name='us-west-2')
""":type: pyboto3.cloudformation """


def check_cloudformation(path):
    try:
        with open(path, 'r') as fp:
            cfn.validate_template(TemplateBody=fp.read())
        return True
    except (BotoCoreError, ClientError) as e:
        print >> sys.stderr, "%s: %s" % (path, e)
        return False


def main():
    paths = sys.argv[1:]

    failed = False
    for path in paths:
        # TODO: This file exceeds the maximum length of 51,200 bytes. Implement a way to include this in the check
        if 'roles_xgemail_template.json' in path or 'sg_xgemail_template.json' in path or 'xgemail_messaging_a_template.json' in path or 'as_customer_delivery_template.json' in path or 'as_customer_xdelivery_template.json' in path:
            continue
        if not check_cloudformation(path):
            failed = True

    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    main()
