#!/bin/bash
# vim: autoindent expandtab tabstop=4 softtabstop=4 shiftwidth=4 filetype=python

# Copyright 2016, Sophos Limited. All rights reserved.
#
# 'Sophos' and 'Sophos Anti-Virus' are registered trademarks of
# Sophos Limited and Sophos Group.  All other product and company
# names mentioned are trademarks or registered trademarks of their
# respective owners.

# check_erb: Check syntax of each chef template (.erb) file listed on the command line.

# NOTE: This only does VERY basic checking.

rc=0

for f in $*; do
    lhs=$(grep -o '<%' "$f" | wc -l)
    rhs=$(grep -o '%>' "$f" | wc -l)
    if [ "$lhs" = "$rhs" ]; then
        :
    else
        printf '%s: Found %d "<%%" but %d "%%>"\n' "$f" "$lhs" "$rhs"
        rc=1
    fi
done

exit $rc
