az:
  a: eu-west-1a
  b: eu-west-1b
  c: eu-west-1c

xgemail_sxl_dbl: uri.ire1.sophosxl.com
xgemail_sxl_rbl: fur.ire1.sophosxl.com

aws:
  asg:
    is:
      smtpd_auth_xcli_hosts:                    "87.229.68.231"
