name             'sophos-cloud-xgemail'
maintainer       'Sophos'
license          'All rights reserved'
description      'Installs/Configures Postfix'
version          '1.0.0'

depends          'sophos-cloud-mount'
depends          'sophos-cloud-ntpd'
depends          'sophos-msg-snmpd'
depends          'sophos-cloud-java'
