name             'sophos-cloud-xgemail'
maintainer       'Sophos'
license          'All rights reserved'
description      'Installs/Configures Postfix'
version          '0.1.1'

depends          'sophos-cloud-common'
depends          'sophos-cloud-mount'
depends          'sophos-cloud-ntpd'
depends          'sophos-cloud-snmpd'
depends          'sophos-cloud-tomcat'
depends          'sophos-cloud-java'
