---
# CloudEmail IAM Roles for Beta Xdelivery Instances
- name: "Deploy {{stack.iam.role.cloud_email_beta_xdelivery_roles}} to {{account.name}} {{account.region}}"
  cloudformation:
    stack_name:                                 "{{stack.iam.role.cloud_email_beta_xdelivery_roles}}"
    state:                                      present
    region:                                     "{{account.region}}"
    disable_rollback:                           true
    template:                                   "{{template.iam.role.roles_beta_xdelivery_template}}"
    template_parameters:
      Environment:                              "{{account.name}}"
      XgemailMsgHistoryBucketName:              "{{s3.msg_history_bucket}}"
      XgemailMsgHistoryMsBucketName:            "{{s3.msg_history_ms_bucket}}"
      XgemailPolicyBucketName:                  "{{s3.policy_bucket}}"
      XgemailQuarantineBucketName:              "{{s3.quarantine_bucket}}"
      XgemailInternetSubmitBucketName:          "{{s3.internet_submit_bucket}}"
      XgemailCustomerSubmitBucketName:          "{{s3.customer_submit_bucket}}"
      DeliveryDirectorDynamodbTableName:        "{{dynamodb.delivery_director_dynamodb}}"
      DeliveryDirectorBucketName:               "{{s3.delivery_director_bucket}}"
  register: cloud_email_beta_x_iam_output

- name: "Gather {{stack.iam.role.cloud_email_beta_xdelivery_roles}} CloudFormation Stack Output"
  cloudformation_facts:
    stack_name: "{{stack.iam.role.cloud_email_beta_xdelivery_roles}}"
    region: "{{account.region}}"
  register: cloud_email_beta_x_iam_output

# IAM Policy for Beta xdelivery Instances to Kinesis Firehose Delivery Stream
- name: "Deploy Beta EC2 Instances to Kinesis Firehose Log Shipper IAM Policy {{stack.iam.policy.policy_beta_x_publish_to_firehose}} to {{account.name}}-{{account.region}}"
  cloudformation:
    stack_name:              "{{stack.iam.policy.policy_beta_x_publish_to_firehose}}"
    state:                   present
    region:                  "{{account.region}}"
    disable_rollback:        true
    template:                "{{template.iam.policy.policy_publish_to_firehose_template}}"
    template_parameters:
      Environment:           "{{account.name}}"
      FirehoseStreamArn:     "{{kinesis.firehose.arn_prefix}}{{kinesis.firehose.firehose_log_shipper_stream}}"
      RoleNames:             "{{cloud_email_beta_x_iam_output.ansible_facts.cloudformation[stack.iam.role.cloud_email_beta_xdelivery_roles].stack_outputs.XgemailBetaXDeliveryInstanceRole}}"
      PolicyName:            "{{iam.policy.policy_beta_x_publish_to_firehose}}"
  register: log_shipper_policy_output

- name: "Display Kinesis Firehose Log Shipper IAM Policy Stack Output for Beta X instances"
  debug:
    var: log_shipper_policy_output
    verbosity: 2