version: '3'
services:
  internet-submit:
    image: postfix:latest
    container_name: internet-submit
    hostname: internet-submit 
    domainname: local.sandbox.hydra.sophos.com
    ports:
      - '25:25' #SMTP
    environment:
      - HOSTNAME_EXTERNAL=internet-submit
      - INSTANCE_TYPE=submit
      - DEFAULT_REGION=local
      - DEFAULT_ENVIRONMENT=sandbox
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ~/g/email/xgemail-infrastructure/cookbooks:/opt/sophos/xgemail/cookbooks:ro
networks:
  default:
    external:
      name: nova_novanet
