version: '3'
services:
  postfix:
    image: 283871543274.dkr.ecr.us-east-2.amazonaws.com/xgemail/postfix:latest
    container_name: postfix
    hostname: submit 
    domainname: sandbox.sophos
    ports:
      - '25:25' #SMTP
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:514"
        syslog-format: rfc3164
        tag: postfix
    environment:
      - HOSTNAME_EXTERNAL=postfix
      - DEFAULT_REGION=local
      - DEBUG=1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/g/email/xgemail-infrastructure/docker/postfix/etc/postfix-is:/etc/postfix-is:rw
      - ~/g/email/xgemail-infrastructure/docker/postfix/etc/ssl:/etc/ssl:ro
networks:
  default:
    external:
      name: nova_novanet
